export interface Festival2026 {
  id: string;
  name: string;
  nameHi: string;
  englishName: string;
  hindiName: string;
  date: string; // ISO format: YYYY-MM-DD
  year: number;
  month: number;
  day: number;
  dayOfWeek: string;
  dayOfWeekHi: string;
  dateStrEn: string;
  dateStrHi: string;
  tithi: string;
  tithiHi: string;
  description: string;
  descriptionHi: string;
  category: string;
  categoryHi: string;
  imageUrl: string;
  url: string;
}

export interface CalendarMonth2026 {
  month: number;
  monthName: string;
  monthNameHi: string;
  festivals: Festival2026[];
}

const MONTH_NAMES: { en: string; hi: string }[] = [
  { en: 'January', hi: 'जनवरी' },
  { en: 'February', hi: 'फरवरी' },
  { en: 'March', hi: 'मार्च' },
  { en: 'April', hi: 'अप्रैल' },
  { en: 'May', hi: 'मई' },
  { en: 'June', hi: 'जून' },
  { en: 'July', hi: 'जुलाई' },
  { en: 'August', hi: 'अगस्त' },
  { en: 'September', hi: 'सितंबर' },
  { en: 'October', hi: 'अक्टूबर' },
  { en: 'November', hi: 'नवंबर' },
  { en: 'December', hi: 'दिसंबर' },
];
export const CALENDAR_2026: Festival2026[] = [
  {
    id: 'shattila_ekadashi_2026_01_13',
    name: 'Shattila Ekadashi',
    nameHi: 'षट्तिला एकादशी',
    englishName: 'Shattila Ekadashi',
    hindiName: 'षट्तिला एकादशी',
    date: '2026-01-13',
    year: 2026,
    month: 1,
    day: 13,
    dayOfWeek: 'Tuesday',
    dayOfWeekHi: 'मंगलवार',
    dateStrEn: 'January 13, 2026, Tuesday',
    dateStrHi: 'जनवरी 13, 2026, मंगलवार',
    tithi: 'Magha, Krishna Ekadashi',
    tithiHi: 'माघ, कृष्ण एकादशी',
    description: 'Magha, Krishna Ekadashi',
    descriptionHi: 'माघ, कृष्ण एकादशी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/ekadashis/shattila/shattila-ekadashi-date-time.html?year=2026',
  },
  {
    id: 'makara_sankranti_2026_01_14',
    name: 'Makara Sankranti',
    nameHi: 'मकर संक्रांति',
    englishName: 'Makara Sankranti',
    hindiName: 'मकर संक्रांति',
    date: '2026-01-14',
    year: 2026,
    month: 1,
    day: 14,
    dayOfWeek: 'Wednesday',
    dayOfWeekHi: 'बुधवार',
    dateStrEn: 'January 14, 2026, Wednesday',
    dateStrHi: 'जनवरी 14, 2026, बुधवार',
    tithi: 'Dhanu to Makara transit of Sun',
    tithiHi: 'सूर्य का धनु से मकर राशि में प्रवेश',
    description: 'Dhanu to Makara transit of Sun',
    descriptionHi: 'सूर्य का धनु से मकर राशि में प्रवेश',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/sankranti/makar-sankranti-date-time.html?year=2026',
  },

  {
    id: 'vasant_panchami_2026_01_23',
    name: 'Vasant Panchami',
    nameHi: 'वसन्त पञ्चमी',
    englishName: 'Vasant Panchami',
    hindiName: 'वसन्त पञ्चमी',
    date: '2026-01-23',
    year: 2026,
    month: 1,
    day: 23,
    dayOfWeek: 'Friday',
    dayOfWeekHi: 'शुक्रवार',
    dateStrEn: 'January 23, 2026, Friday',
    dateStrHi: 'जनवरी 23, 2026, शुक्रवार',
    tithi: 'Magha, Shukla Panchami',
    tithiHi: 'माघ, शुक्ल पञ्चमी',
    description: 'Magha, Shukla Panchami',
    descriptionHi: 'माघ, शुक्ल पञ्चमी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/festivals/vasant-panchami/vasant-panchami-puja-date-time.html?year=2026',
  },

  {
    id: 'jaya_ekadashi_2026_01_28',
    name: 'Jaya Ekadashi',
    nameHi: 'जया एकादशी',
    englishName: 'Jaya Ekadashi',
    hindiName: 'जया एकादशी',
    date: '2026-01-28',
    year: 2026,
    month: 1,
    day: 28,
    dayOfWeek: 'Wednesday',
    dayOfWeekHi: 'बुधवार',
    dateStrEn: 'January 28, 2026, Wednesday',
    dateStrHi: 'जनवरी 28, 2026, बुधवार',
    tithi: 'Magha, Shukla Ekadashi',
    tithiHi: 'माघ, शुक्ल एकादशी',
    description: 'Magha, Shukla Ekadashi',
    descriptionHi: 'माघ, शुक्ल एकादशी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/ekadashis/jaya/jaya-ekadashi-date-time.html?year=2026',
  },

  {
    id: 'vijaya_ekadashi_2026_02_12',
    name: 'Vijaya Ekadashi',
    nameHi: 'विजया एकादशी',
    englishName: 'Vijaya Ekadashi',
    hindiName: 'विजया एकादशी',
    date: '2026-02-12',
    year: 2026,
    month: 2,
    day: 12,
    dayOfWeek: 'Thursday',
    dayOfWeekHi: 'बृहस्पतिवार',
    dateStrEn: 'February 12, 2026, Thursday',
    dateStrHi: 'फरवरी 12, 2026, बृहस्पतिवार',
    tithi: 'Phalguna, Krishna Ekadashi',
    tithiHi: 'फाल्गुन, कृष्ण एकादशी',
    description: 'Phalguna, Krishna Ekadashi',
    descriptionHi: 'फाल्गुन, कृष्ण एकादशी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/ekadashis/vijaya/vijaya-ekadashi-date-time.html?year=2026',
  },
  {
    id: 'maha_shivaratri_2026_02_15',
    name: 'Maha Shivaratri',
    nameHi: 'महाशिवरात्रि',
    englishName: 'Maha Shivaratri',
    hindiName: 'महाशिवरात्रि',
    date: '2026-02-15',
    year: 2026,
    month: 2,
    day: 15,
    dayOfWeek: 'Sunday',
    dayOfWeekHi: 'रविवार',
    dateStrEn: 'February 15, 2026, Sunday',
    dateStrHi: 'फरवरी 15, 2026, रविवार',
    tithi: 'Phalguna, Krishna Chaturdashi',
    tithiHi: 'फाल्गुन, कृष्ण चतुर्दशी',
    description: 'Phalguna, Krishna Chaturdashi',
    descriptionHi: 'फाल्गुन, कृष्ण चतुर्दशी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/festivals/maha-shivaratri/maha-shivaratri-date-time.html?year=2026',
  },

  {
    id: 'amalaki_ekadashi_2026_02_27',
    name: 'Amalaki Ekadashi',
    nameHi: 'आमलकी एकादशी',
    englishName: 'Amalaki Ekadashi',
    hindiName: 'आमलकी एकादशी',
    date: '2026-02-27',
    year: 2026,
    month: 2,
    day: 27,
    dayOfWeek: 'Friday',
    dayOfWeekHi: 'शुक्रवार',
    dateStrEn: 'February 27, 2026, Friday',
    dateStrHi: 'फरवरी 27, 2026, शुक्रवार',
    tithi: 'Phalguna, Shukla Ekadashi',
    tithiHi: 'फाल्गुन, शुक्ल एकादशी',
    description: 'Phalguna, Shukla Ekadashi',
    descriptionHi: 'फाल्गुन, शुक्ल एकादशी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/ekadashis/amalaki/amalaki-ekadashi-date-time.html?year=2026',
  },
  {
    id: 'chhoti_holi_2026_03_02',
    name: 'Chhoti Holi',
    nameHi: 'छोटी होली',
    englishName: 'Chhoti Holi',
    hindiName: 'छोटी होली',
    date: '2026-03-02',
    year: 2026,
    month: 3,
    day: 2,
    dayOfWeek: 'Monday',
    dayOfWeekHi: 'सोमवार',
    dateStrEn: 'March 2, 2026, Monday',
    dateStrHi: 'मार्च 2, 2026, सोमवार',
    tithi: 'Phalguna, Shukla Purnima',
    tithiHi: 'फाल्गुन, शुक्ल पूर्णिमा',
    description: 'Phalguna, Shukla Purnima',
    descriptionHi: 'फाल्गुन, शुक्ल पूर्णिमा',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/festivals/holi/festivals-holika-dahan-timings.html?year=2026',
  },
  {
    id: 'holika_dahan_2026_03_02',
    name: 'Holika Dahan',
    nameHi: 'होलिका दहन',
    englishName: 'Holika Dahan',
    hindiName: 'होलिका दहन',
    date: '2026-03-02',
    year: 2026,
    month: 3,
    day: 2,
    dayOfWeek: 'Monday',
    dayOfWeekHi: 'सोमवार',
    dateStrEn: 'March 2, 2026, Monday',
    dateStrHi: 'मार्च 2, 2026, सोमवार',
    tithi: 'Phalguna, Shukla Purnima',
    tithiHi: 'फाल्गुन, शुक्ल पूर्णिमा',
    description: 'Phalguna, Shukla Purnima',
    descriptionHi: 'फाल्गुन, शुक्ल पूर्णिमा',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/festivals/holi/festivals-holika-dahan-timings.html?year=2026',
  },

  {
    id: 'holi_2026_03_03',
    name: 'Holi',
    nameHi: 'होली',
    englishName: 'Holi',
    hindiName: 'होली',
    date: '2026-03-03',
    year: 2026,
    month: 3,
    day: 3,
    dayOfWeek: 'Tuesday',
    dayOfWeekHi: 'मंगलवार',
    dateStrEn: 'March 3, 2026, Tuesday',
    dateStrHi: 'मार्च 3, 2026, मंगलवार',
    tithi: 'Chaitra, Krishna Pratipada',
    tithiHi: 'फाल्गुन, शुक्ल पूर्णिमा',
    description: 'Phalguna, Shukla Purnima',
    descriptionHi: 'फाल्गुन, शुक्ल पूर्णिमा',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/festivals/holi/festivals-holi-rangwali.html?year=2026',
  },

  {
    id: 'papamochani_ekadashi_2026_03_14',
    name: 'Papamochani Ekadashi',
    nameHi: 'पापमोचिनी एकादशी',
    englishName: 'Papamochani Ekadashi',
    hindiName: 'पापमोचिनी एकादशी',
    date: '2026-03-14',
    year: 2026,
    month: 3,
    day: 14,
    dayOfWeek: 'Saturday',
    dayOfWeekHi: 'शनिवार',
    dateStrEn: 'March 14, 2026, Saturday',
    dateStrHi: 'मार्च 14, 2026, शनिवार',
    tithi: 'Chaitra, Krishna Ekadashi',
    tithiHi: 'चैत्र, कृष्ण एकादशी',
    description: 'Chaitra, Krishna Ekadashi',
    descriptionHi: 'चैत्र, कृष्ण एकादशी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/ekadashis/papmochani/papmochani-ekadashi-date-time.html?year=2026',
  },
  {
    id: 'chaitra_navratri_2026_03_19',
    name: 'Chaitra Navratri',
    nameHi: 'चैत्र नवरात्रि',
    englishName: 'Chaitra Navratri',
    hindiName: 'चैत्र नवरात्रि',
    date: '2026-03-19',
    year: 2026,
    month: 3,
    day: 19,
    dayOfWeek: 'Thursday',
    dayOfWeekHi: 'बृहस्पतिवार',
    dateStrEn: 'March 19, 2026, Thursday',
    dateStrHi: 'मार्च 19, 2026, बृहस्पतिवार',
    tithi: 'Chaitra, Shukla Pratipada',
    tithiHi: 'चैत्र, शुक्ल प्रतिपदा',
    description: 'Chaitra, Shukla Pratipada',
    descriptionHi: 'चैत्र, शुक्ल प्रतिपदा',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/navratri/chaitra-navratri-ghatasthapana.html?year=2026',
  },

  {
    id: 'gauri_puja_2026_03_21',
    name: 'Gauri Puja',
    nameHi: 'गौरी पूजा',
    englishName: 'Gauri Puja',
    hindiName: 'गौरी पूजा',
    date: '2026-03-21',
    year: 2026,
    month: 3,
    day: 21,
    dayOfWeek: 'Saturday',
    dayOfWeekHi: 'शनिवार',
    dateStrEn: 'March 21, 2026, Saturday',
    dateStrHi: 'मार्च 21, 2026, शनिवार',
    tithi: 'Chaitra, Shukla Tritiya',
    tithiHi: 'चैत्र, शुक्ल तृतीया',
    description: 'Chaitra, Shukla Tritiya',
    descriptionHi: 'चैत्र, शुक्ल तृतीया',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/festivals/gangaur/gangaur-date-time.html?year=2026',
  },

  {
    id: 'rama_navami_2026_03_26',
    name: 'Rama Navami',
    nameHi: 'राम नवमी',
    englishName: 'Rama Navami',
    hindiName: 'राम नवमी',
    date: '2026-03-26',
    year: 2026,
    month: 3,
    day: 26,
    dayOfWeek: 'Thursday',
    dayOfWeekHi: 'बृहस्पतिवार',
    dateStrEn: 'March 26, 2026, Thursday',
    dateStrHi: 'मार्च 26, 2026, बृहस्पतिवार',
    tithi: 'Chaitra, Shukla Navami',
    tithiHi: 'चैत्र, शुक्ल नवमी',
    description: 'Chaitra, Shukla Navami',
    descriptionHi: 'चैत्र, शुक्ल नवमी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/dashavatara/rama-navami/rama-navami-date-time.html?year=2026',
  },

  {
    id: 'kamada_ekadashi_2026_03_28',
    name: 'Kamada Ekadashi',
    nameHi: 'कामदा एकादशी',
    englishName: 'Kamada Ekadashi',
    hindiName: 'कामदा एकादशी',
    date: '2026-03-28',
    year: 2026,
    month: 3,
    day: 28,
    dayOfWeek: 'Saturday',
    dayOfWeekHi: 'शनिवार',
    dateStrEn: 'March 28, 2026, Saturday',
    dateStrHi: 'मार्च 28, 2026, शनिवार',
    tithi: 'Chaitra, Shukla Ekadashi',
    tithiHi: 'चैत्र, शुक्ल एकादशी',
    description: 'Chaitra, Shukla Ekadashi',
    descriptionHi: 'चैत्र, शुक्ल एकादशी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/ekadashis/kamada/kamada-ekadashi-date-time.html?year=2026',
  },

  {
    id: 'hanuman_jayanti_2026_04_01',
    name: 'Hanuman Jayanti',
    nameHi: 'हनुमान जयन्ती',
    englishName: 'Hanuman Jayanti',
    hindiName: 'हनुमान जयन्ती',
    date: '2026-04-01',
    year: 2026,
    month: 4,
    day: 1,
    dayOfWeek: 'Wednesday',
    dayOfWeekHi: 'बुधवार',
    dateStrEn: 'April 1, 2026, Wednesday',
    dateStrHi: 'अप्रैल 1, 2026, बुधवार',
    tithi: 'Chaitra, Shukla Purnima',
    tithiHi: 'चैत्र, शुक्ल पूर्णिमा',
    description: 'Chaitra, Shukla Purnima',
    descriptionHi: 'चैत्र, शुक्ल पूर्णिमा',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/festivals/hanuman-jayanti/hanuman-jayanti-date-time.html?year=2026',
  },

  {
    id: 'varuthini_ekadashi_2026_04_13',
    name: 'Varuthini Ekadashi',
    nameHi: 'वरुथिनी एकादशी',
    englishName: 'Varuthini Ekadashi',
    hindiName: 'वरुथिनी एकादशी',
    date: '2026-04-13',
    year: 2026,
    month: 4,
    day: 13,
    dayOfWeek: 'Monday',
    dayOfWeekHi: 'सोमवार',
    dateStrEn: 'April 13, 2026, Monday',
    dateStrHi: 'अप्रैल 13, 2026, सोमवार',
    tithi: 'Vaishakha, Krishna Ekadashi',
    tithiHi: 'वैशाख, कृष्ण एकादशी',
    description: 'Vaishakha, Krishna Ekadashi',
    descriptionHi: 'वैशाख, कृष्ण एकादशी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/ekadashis/varuthini/varuthini-ekadashi-date-time.html?year=2026',
  },

  {
    id: 'mohini_ekadashi_2026_04_27',
    name: 'Mohini Ekadashi',
    nameHi: 'मोहिनी एकादशी',
    englishName: 'Mohini Ekadashi',
    hindiName: 'मोहिनी एकादशी',
    date: '2026-04-27',
    year: 2026,
    month: 4,
    day: 27,
    dayOfWeek: 'Monday',
    dayOfWeekHi: 'सोमवार',
    dateStrEn: 'April 27, 2026, Monday',
    dateStrHi: 'अप्रैल 27, 2026, सोमवार',
    tithi: 'Vaishakha, Shukla Ekadashi',
    tithiHi: 'वैशाख, शुक्ल एकादशी',
    description: 'Vaishakha, Shukla Ekadashi',
    descriptionHi: 'वैशाख, शुक्ल एकादशी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/ekadashis/mohini/mohini-ekadashi-date-time.html?year=2026',
  },

  {
    id: 'apara_ekadashi_2026_05_12',
    name: 'Apara Ekadashi',
    nameHi: 'अपरा एकादशी',
    englishName: 'Apara Ekadashi',
    hindiName: 'अपरा एकादशी',
    date: '2026-05-12',
    year: 2026,
    month: 5,
    day: 12,
    dayOfWeek: 'Tuesday',
    dayOfWeekHi: 'मंगलवार',
    dateStrEn: 'May 12, 2026, Tuesday',
    dateStrHi: 'मई 12, 2026, मंगलवार',
    tithi: 'Jyeshtha, Krishna Ekadashi',
    tithiHi: 'ज्येष्ठ, कृष्ण एकादशी',
    description: 'Jyeshtha, Krishna Ekadashi',
    descriptionHi: 'ज्येष्ठ, कृष्ण एकादशी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/ekadashis/apara/apara-ekadashi-date-time.html?year=2026',
  },

  {
    id: 'padmini_ekadashi_2026_05_26',
    name: 'Padmini Ekadashi',
    nameHi: 'पद्मिनी एकादशी',
    englishName: 'Padmini Ekadashi',
    hindiName: 'पद्मिनी एकादशी',
    date: '2026-05-26',
    year: 2026,
    month: 5,
    day: 26,
    dayOfWeek: 'Tuesday',
    dayOfWeekHi: 'मंगलवार',
    dateStrEn: 'May 26, 2026, Tuesday',
    dateStrHi: 'मई 26, 2026, मंगलवार',
    tithi: 'Jyeshtha Adhika, Shukla Ekadashi',
    tithiHi: 'ज्येष्ठ अधिक, शुक्ल एकादशी',
    description: 'Jyeshtha Adhika, Shukla Ekadashi',
    descriptionHi: 'ज्येष्ठ अधिक, शुक्ल एकादशी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/ekadashis/padmini/padmini-ekadashi-date-time.html?date=26/05/2026',
  },

  {
    id: 'parama_ekadashi_2026_06_11',
    name: 'Parama Ekadashi',
    nameHi: 'परमा एकादशी',
    englishName: 'Parama Ekadashi',
    hindiName: 'परमा एकादशी',
    date: '2026-06-11',
    year: 2026,
    month: 6,
    day: 11,
    dayOfWeek: 'Thursday',
    dayOfWeekHi: 'बृहस्पतिवार',
    dateStrEn: 'June 11, 2026, Thursday',
    dateStrHi: 'जून 11, 2026, बृहस्पतिवार',
    tithi: 'Jyeshtha Adhika, Krishna Ekadashi',
    tithiHi: 'ज्येष्ठ अधिक, कृष्ण एकादशी',
    description: 'Jyeshtha Adhika, Krishna Ekadashi',
    descriptionHi: 'ज्येष्ठ अधिक, कृष्ण एकादशी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/ekadashis/parama/parama-ekadashi-date-time.html?date=11/06/2026',
  },

  {
    id: 'nirjala_ekadashi_2026_06_25',
    name: 'Nirjala Ekadashi',
    nameHi: 'निर्जला एकादशी',
    englishName: 'Nirjala Ekadashi',
    hindiName: 'निर्जला एकादशी',
    date: '2026-06-25',
    year: 2026,
    month: 6,
    day: 25,
    dayOfWeek: 'Thursday',
    dayOfWeekHi: 'बृहस्पतिवार',
    dateStrEn: 'June 25, 2026, Thursday',
    dateStrHi: 'जून 25, 2026, बृहस्पतिवार',
    tithi: 'Jyeshtha, Shukla Ekadashi',
    tithiHi: 'ज्येष्ठ, शुक्ल एकादशी',
    description: 'Jyeshtha, Shukla Ekadashi',
    descriptionHi: 'ज्येष्ठ, शुक्ल एकादशी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/ekadashis/nirjala/nirjala-ekadashi-date-time.html?year=2026',
  },

  {
    id: 'jagannath_rathyatra_2026_07_15',
    name: 'Jagannath Rathyatra',
    nameHi: 'जगन्नाथ रथयात्रा',
    englishName: 'Jagannath Rathyatra',
    hindiName: 'जगन्नाथ रथयात्रा',
    date: '2026-07-15',
    year: 2026,
    month: 7,
    day: 15,
    dayOfWeek: 'Wednesday',
    dayOfWeekHi: 'बुधवार',
    dateStrEn: 'July 15, 2026, Wednesday',
    dateStrHi: 'जुलाई 15, 2026, बुधवार',
    tithi: 'Ashadha, Shukla Dwitiya',
    tithiHi: 'आषाढ़, शुक्ल द्वितीया',
    description: 'Ashadha, Shukla Dwitiya',
    descriptionHi: 'आषाढ़, शुक्ल द्वितीया',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/festivals/ratha-yatra/jagannatha-rathayatra-date-time.html?year=2026',
  },

  {
    id: 'devshayani_ekadashi_2026_07_24',
    name: 'Devshayani Ekadashi',
    nameHi: 'देवशयनी एकादशी',
    englishName: 'Devshayani Ekadashi',
    hindiName: 'देवशयनी एकादशी',
    date: '2026-07-24',
    year: 2026,
    month: 7,
    day: 24,
    dayOfWeek: 'Friday',
    dayOfWeekHi: 'शुक्रवार',
    dateStrEn: 'July 24, 2026, Friday',
    dateStrHi: 'जुलाई 24, 2026, शुक्रवार',
    tithi: 'Ashadha, Shukla Ekadashi',
    tithiHi: 'आषाढ़, शुक्ल एकादशी',
    description: 'Ashadha, Shukla Ekadashi',
    descriptionHi: 'आषाढ़, शुक्ल एकादशी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/ekadashis/devshayani/devshayani-ekadashi-date-time.html?year=2026',
  },

  {
    id: 'kamika_ekadashi_2026_08_08',
    name: 'Kamika Ekadashi',
    nameHi: 'कामिका एकादशी',
    englishName: 'Kamika Ekadashi',
    hindiName: 'कामिका एकादशी',
    date: '2026-08-08',
    year: 2026,
    month: 8,
    day: 8,
    dayOfWeek: 'Saturday',
    dayOfWeekHi: 'शनिवार',
    dateStrEn: 'August 8, 2026, Saturday',
    dateStrHi: 'अगस्त 8, 2026, शनिवार',
    tithi: 'Shravana, Krishna Ekadashi',
    tithiHi: 'श्रावण, कृष्ण एकादशी',
    description: 'Shravana, Krishna Ekadashi',
    descriptionHi: 'श्रावण, कृष्ण एकादशी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/ekadashis/kamika/kamika-ekadashi-date-time.html?year=2026',
  },

  {
    id: 'hariyali_teej_2026_08_15',
    name: 'Hariyali Teej',
    nameHi: 'हरियाली तीज',
    englishName: 'Hariyali Teej',
    hindiName: 'हरियाली तीज',
    date: '2026-08-15',
    year: 2026,
    month: 8,
    day: 15,
    dayOfWeek: 'Saturday',
    dayOfWeekHi: 'शनिवार',
    dateStrEn: 'August 15, 2026, Saturday',
    dateStrHi: 'अगस्त 15, 2026, शनिवार',
    tithi: 'Shravana, Shukla Tritiya',
    tithiHi: 'श्रावण, शुक्ल तृतीया',
    description: 'Shravana, Shukla Tritiya',
    descriptionHi: 'श्रावण, शुक्ल तृतीया',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/festivals/teej/hariyali-teej-date-time.html?year=2026',
  },
  {
    id: 'nag_panchami_2026_08_16',
    name: 'Nag Panchami',
    nameHi: 'नाग पंचमी',
    englishName: 'Nag Panchami',
    hindiName: 'नाग पंचमी',
    date: '2026-08-16',
    year: 2026,
    month: 8,
    day: 16,
    dayOfWeek: 'Sunday',
    dayOfWeekHi: 'रविवार',
    dateStrEn: 'August 16, 2026, Sunday',
    dateStrHi: 'अगस्त 16, 2026, रविवार',
    tithi: 'Shravana, Shukla Panchami',
    tithiHi: 'श्रावण, शुक्ल पञ्चमी',
    description: 'Shravana, Shukla Panchami',
    descriptionHi: 'श्रावण, शुक्ल पञ्चमी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/festivals/nag-panchami/nag-panchami-date-time.html?year=2026',
  },

  {
    id: 'shravana_putrada_ekadashi_2026_08_23',
    name: 'Shravana Putrada Ekadashi',
    nameHi: 'श्रावण पुत्रदा एकादशी',
    englishName: 'Shravana Putrada Ekadashi',
    hindiName: 'श्रावण पुत्रदा एकादशी',
    date: '2026-08-23',
    year: 2026,
    month: 8,
    day: 23,
    dayOfWeek: 'Sunday',
    dayOfWeekHi: 'रविवार',
    dateStrEn: 'August 23, 2026, Sunday',
    dateStrHi: 'अगस्त 23, 2026, रविवार',
    tithi: 'Shravana, Shukla Ekadashi',
    tithiHi: 'श्रावण, शुक्ल एकादशी',
    description: 'Shravana, Shukla Ekadashi',
    descriptionHi: 'श्रावण, शुक्ल एकादशी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/ekadashis/putrada/shravana-putrada-ekadashi-date-time.html?year=2026',
  },

  {
    id: 'raksha_bandhan_2026_08_27',
    name: 'Raksha Bandhan',
    nameHi: 'रक्षा बन्धन',
    englishName: 'Raksha Bandhan',
    hindiName: 'रक्षा बन्धन',
    date: '2026-08-27',
    year: 2026,
    month: 8,
    day: 27,
    dayOfWeek: 'Thursday',
    dayOfWeekHi: 'बृहस्पतिवार',
    dateStrEn: 'August 27, 2026, Thursday',
    dateStrHi: 'अगस्त 27, 2026, बृहस्पतिवार',
    tithi: 'Shravana, Shukla Purnima',
    tithiHi: 'श्रावण, शुक्ल पूर्णिमा',
    description: 'Shravana, Shukla Purnima',
    descriptionHi: 'श्रावण, शुक्ल पूर्णिमा',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/festivals/raksha-bandhan/raksha-bandhan-date-time.html?year=2026',
  },

  {
    id: 'aja_ekadashi_2026_09_06',
    name: 'Aja Ekadashi',
    nameHi: 'अजा एकादशी',
    englishName: 'Aja Ekadashi',
    hindiName: 'अजा एकादशी',
    date: '2026-09-06',
    year: 2026,
    month: 9,
    day: 6,
    dayOfWeek: 'Sunday',
    dayOfWeekHi: 'रविवार',
    dateStrEn: 'September 6, 2026, Sunday',
    dateStrHi: 'सितंबर 6, 2026, रविवार',
    tithi: 'Bhadrapada, Krishna Ekadashi',
    tithiHi: 'भाद्रपद, कृष्ण एकादशी',
    description: 'Bhadrapada, Krishna Ekadashi',
    descriptionHi: 'भाद्रपद, कृष्ण एकादशी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/ekadashis/aja/aja-ekadashi-date-time.html?year=2026',
  },
  {
    id: 'gauna_aja_ekadashi_2026_09_07',
    name: 'Gauna Aja Ekadashi',
    nameHi: 'गौण अजा एकादशी',
    englishName: 'Gauna Aja Ekadashi',
    hindiName: 'गौण अजा एकादशी',
    date: '2026-09-07',
    year: 2026,
    month: 9,
    day: 7,
    dayOfWeek: 'Monday',
    dayOfWeekHi: 'सोमवार',
    dateStrEn: 'September 7, 2026, Monday',
    dateStrHi: 'सितंबर 7, 2026, सोमवार',
    tithi: 'Bhadrapada, Krishna Ekadashi',
    tithiHi: 'भाद्रपद, कृष्ण एकादशी',
    description: 'Bhadrapada, Krishna Ekadashi',
    descriptionHi: 'भाद्रपद, कृष्ण एकादशी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/ekadashis/aja/aja-ekadashi-date-time.html?year=2026',
  },

  {
    id: 'ganesh_chaturthi_2026_09_14',
    name: 'Ganesh Chaturthi',
    nameHi: 'गणेश चतुर्थी',
    englishName: 'Ganesh Chaturthi',
    hindiName: 'गणेश चतुर्थी',
    date: '2026-09-14',
    year: 2026,
    month: 9,
    day: 14,
    dayOfWeek: 'Monday',
    dayOfWeekHi: 'सोमवार',
    dateStrEn: 'September 14, 2026, Monday',
    dateStrHi: 'सितंबर 14, 2026, सोमवार',
    tithi: 'Bhadrapada, Shukla Chaturthi',
    tithiHi: 'भाद्रपद, शुक्ल चतुर्थी',
    description: 'Bhadrapada, Shukla Chaturthi',
    descriptionHi: 'भाद्रपद, शुक्ल चतुर्थी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/festivals/ganesh-chaturthi/ganesh-chaturthi-date-time.html?year=2026',
  },

  {
    id: 'vishwakarma_puja_2026_09_16',
    name: 'Vishwakarma Puja',
    nameHi: 'विश्वकर्मा पूजा',
    englishName: 'Vishwakarma Puja',
    hindiName: 'विश्वकर्मा पूजा',
    date: '2026-09-16',
    year: 2026,
    month: 9,
    day: 16,
    dayOfWeek: 'Wednesday',
    dayOfWeekHi: 'बुधवार',
    dateStrEn: 'September 16, 2026, Wednesday',
    dateStrHi: 'सितंबर 16, 2026, बुधवार',
    tithi: 'on Kanya Sankranti day',
    tithiHi: 'कन्या संक्रान्ति के दिन',
    description: 'on Kanya Sankranti day',
    descriptionHi: 'कन्या संक्रान्ति के दिन',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/sankranti/vishwakarma-puja-date-time.html?year=2026',
  },
  {
    id: 'radha_ashtami_2026_09_18',
    name: 'Radha Ashtami',
    nameHi: 'राधा अष्टमी',
    englishName: 'Radha Ashtami',
    hindiName: 'राधा अष्टमी',
    date: '2026-09-18',
    year: 2026,
    month: 9,
    day: 18,
    dayOfWeek: 'Friday',
    dayOfWeekHi: 'शुक्रवार',
    dateStrEn: 'September 18, 2026, Friday',
    dateStrHi: 'सितंबर 18, 2026, शुक्रवार',
    tithi: 'Bhadrapada, Shukla Ashtami',
    tithiHi: 'भाद्रपद, शुक्ल अष्टमी',
    description: 'Bhadrapada, Shukla Ashtami',
    descriptionHi: 'भाद्रपद, शुक्ल अष्टमी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/festivals/radha-ashtami/radha-ashtami-date-time.html?year=2026',
  },
  {
    id: 'parsva_ekadashi_2026_09_22',
    name: 'Parsva Ekadashi',
    nameHi: 'पार्श्व एकादशी',
    englishName: 'Parsva Ekadashi',
    hindiName: 'पार्श्व एकादशी',
    date: '2026-09-22',
    year: 2026,
    month: 9,
    day: 22,
    dayOfWeek: 'Tuesday',
    dayOfWeekHi: 'मंगलवार',
    dateStrEn: 'September 22, 2026, Tuesday',
    dateStrHi: 'सितंबर 22, 2026, मंगलवार',
    tithi: 'Bhadrapada, Shukla Ekadashi',
    tithiHi: 'भाद्रपद, शुक्ल एकादशी',
    description: 'Bhadrapada, Shukla Ekadashi',
    descriptionHi: 'भाद्रपद, शुक्ल एकादशी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/ekadashis/parivartini/parivartini-ekadashi-date-time.html?year=2026',
  },

  {
    id: 'ganesh_visarjan_2026_09_25',
    name: 'Ganesh Visarjan',
    nameHi: 'गणेश विसर्जन',
    englishName: 'Ganesh Visarjan',
    hindiName: 'गणेश विसर्जन',
    date: '2026-09-25',
    year: 2026,
    month: 9,
    day: 25,
    dayOfWeek: 'Friday',
    dayOfWeekHi: 'शुक्रवार',
    dateStrEn: 'September 25, 2026, Friday',
    dateStrHi: 'सितंबर 25, 2026, शुक्रवार',
    tithi: 'Bhadrapada, Shukla Chaturdashi',
    tithiHi: 'भाद्रपद, शुक्ल चतुर्दशी',
    description: 'Bhadrapada, Shukla Chaturdashi',
    descriptionHi: 'भाद्रपद, शुक्ल चतुर्दशी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/festivals/ganesh-visarjan/ganesh-visarjan-date-time.html?year=2026',
  },

  {
    id: 'indira_ekadashi_2026_10_06',
    name: 'Indira Ekadashi',
    nameHi: 'इन्दिरा एकादशी',
    englishName: 'Indira Ekadashi',
    hindiName: 'इन्दिरा एकादशी',
    date: '2026-10-06',
    year: 2026,
    month: 10,
    day: 6,
    dayOfWeek: 'Tuesday',
    dayOfWeekHi: 'मंगलवार',
    dateStrEn: 'October 6, 2026, Tuesday',
    dateStrHi: 'अक्टूबर 6, 2026, मंगलवार',
    tithi: 'Ashwina, Krishna Ekadashi',
    tithiHi: 'आश्विन, कृष्ण एकादशी',
    description: 'Ashwina, Krishna Ekadashi',
    descriptionHi: 'आश्विन, कृष्ण एकादशी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/ekadashis/indira/indira-ekadashi-date-time.html?year=2026',
  },

  {
    id: 'navratri_begins_2026_10_11',
    name: 'Navratri Begins',
    nameHi: 'नवरात्रि प्रारम्भ',
    englishName: 'Navratri Begins',
    hindiName: 'नवरात्रि प्रारम्भ',
    date: '2026-10-11',
    year: 2026,
    month: 10,
    day: 11,
    dayOfWeek: 'Sunday',
    dayOfWeekHi: 'रविवार',
    dateStrEn: 'October 11, 2026, Sunday',
    dateStrHi: 'अक्टूबर 11, 2026, रविवार',
    tithi: 'Ashwina, Shukla Pratipada',
    tithiHi: 'आश्विन, शुक्ल प्रतिपदा',
    description: 'Ashwina, Shukla Pratipada',
    descriptionHi: 'आश्विन, शुक्ल प्रतिपदा',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/navratri/navratri-date.html?year=2026',
  },

  {
    id: 'dussehra_2026_10_20',
    name: 'Dussehra',
    nameHi: 'दशहरा',
    englishName: 'Dussehra',
    hindiName: 'दशहरा',
    date: '2026-10-20',
    year: 2026,
    month: 10,
    day: 20,
    dayOfWeek: 'Tuesday',
    dayOfWeekHi: 'मंगलवार',
    dateStrEn: 'October 20, 2026, Tuesday',
    dateStrHi: 'अक्टूबर 20, 2026, मंगलवार',
    tithi: 'Ashwina, Shukla Dashami',
    tithiHi: 'आश्विन, शुक्ल दशमी',
    description: 'Ashwina, Shukla Dashami',
    descriptionHi: 'आश्विन, शुक्ल दशमी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/festivals/vijayadashami/vijayadashami-date-time.html?year=2026',
  },

  {
    id: 'papankusha_ekadashi_2026_10_21',
    name: 'Papankusha Ekadashi',
    nameHi: 'पापांकुशा एकादशी',
    englishName: 'Papankusha Ekadashi',
    hindiName: 'पापांकुशा एकादशी',
    date: '2026-10-21',
    year: 2026,
    month: 10,
    day: 21,
    dayOfWeek: 'Wednesday',
    dayOfWeekHi: 'बुधवार',
    dateStrEn: 'October 21, 2026, Wednesday',
    dateStrHi: 'अक्टूबर 21, 2026, बुधवार',
    tithi: 'Ashwina, Shukla Ekadashi',
    tithiHi: 'आश्विन, शुक्ल एकादशी',
    description: 'Ashwina, Shukla Ekadashi',
    descriptionHi: 'आश्विन, शुक्ल एकादशी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/ekadashis/papankusha/papankusha-ekadashi-date-time.html?year=2026',
  },

  {
    id: 'karwa_chauth_2026_10_28',
    name: 'Karwa Chauth',
    nameHi: 'करवा चौथ',
    englishName: 'Karwa Chauth',
    hindiName: 'करवा चौथ',
    date: '2026-10-28',
    year: 2026,
    month: 10,
    day: 28,
    dayOfWeek: 'Wednesday',
    dayOfWeekHi: 'बुधवार',
    dateStrEn: 'October 28, 2026, Wednesday',
    dateStrHi: 'अक्टूबर 28, 2026, बुधवार',
    tithi: 'Kartika, Krishna Chaturthi',
    tithiHi: 'कार्तिक, कृष्ण चतुर्थी',
    description: 'Kartika, Krishna Chaturthi',
    descriptionHi: 'कार्तिक, कृष्ण चतुर्थी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/festivals/karwa-chauth/karwa-chauth-date-time.html?year=2026',
  },

  {
    id: 'rama_ekadashi_2026_11_04',
    name: 'Rama Ekadashi',
    nameHi: 'रमा एकादशी',
    englishName: 'Rama Ekadashi',
    hindiName: 'रमा एकादशी',
    date: '2026-11-04',
    year: 2026,
    month: 11,
    day: 4,
    dayOfWeek: 'Wednesday',
    dayOfWeekHi: 'बुधवार',
    dateStrEn: 'November 4, 2026, Wednesday',
    dateStrHi: 'नवंबर 4, 2026, बुधवार',
    tithi: 'Kartika, Krishna Ekadashi',
    tithiHi: 'कार्तिक, कृष्ण एकादशी',
    description: 'Kartika, Krishna Ekadashi',
    descriptionHi: 'कार्तिक, कृष्ण एकादशी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/ekadashis/rama/rama-ekadashi-date-time.html?year=2026',
  },

  {
    id: 'dhanteras_2026_11_06',
    name: 'Dhanteras',
    nameHi: 'धनतेरस',
    englishName: 'Dhanteras',
    hindiName: 'धनतेरस',
    date: '2026-11-06',
    year: 2026,
    month: 11,
    day: 6,
    dayOfWeek: 'Friday',
    dayOfWeekHi: 'शुक्रवार',
    dateStrEn: 'November 6, 2026, Friday',
    dateStrHi: 'नवंबर 6, 2026, शुक्रवार',
    tithi: 'Kartika, Krishna Trayodashi',
    tithiHi: 'कार्तिक, कृष्ण त्रयोदशी',
    description: 'Kartika, Krishna Trayodashi',
    descriptionHi: 'कार्तिक, कृष्ण त्रयोदशी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/festivals/dhanteras/festivals-dhanteras-puja-timings.html?year=2026',
  },

  {
    id: 'diwali_2026_11_08',
    name: 'Diwali',
    nameHi: 'दीवाली',
    englishName: 'Diwali',
    hindiName: 'दीवाली',
    date: '2026-11-08',
    year: 2026,
    month: 11,
    day: 8,
    dayOfWeek: 'Sunday',
    dayOfWeekHi: 'रविवार',
    dateStrEn: 'November 8, 2026, Sunday',
    dateStrHi: 'नवंबर 8, 2026, रविवार',
    tithi: 'Kartika, Krishna Amavasya',
    tithiHi: 'कार्तिक, कृष्ण अमावस्या',
    description: 'Kartika, Krishna Amavasya',
    descriptionHi: 'कार्तिक, कृष्ण अमावस्या',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/festivals/lakshmipuja/festivals-lakshmipuja-timings.html?year=2026',
  },

  {
    id: 'govardhan_puja_2026_11_09',
    name: 'Govardhan Puja',
    nameHi: 'गोवर्धन पूजा',
    englishName: 'Govardhan Puja',
    hindiName: 'गोवर्धन पूजा',
    date: '2026-11-09',
    year: 2026,
    month: 11,
    day: 9,
    dayOfWeek: 'Monday',
    dayOfWeekHi: 'सोमवार',
    dateStrEn: 'November 9, 2026, Monday',
    dateStrHi: 'नवंबर 9, 2026, सोमवार',
    tithi: 'Kartika, Shukla Pratipada',
    tithiHi: 'कार्तिक, शुक्ल प्रतिपदा',
    description: 'Kartika, Shukla Pratipada',
    descriptionHi: 'कार्तिक, शुक्ल प्रतिपदा',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/festivals/govardhan-puja/govardhan-puja-date-time.html?year=2026',
  },
  {
    id: 'bhaiya_dooj_2026_11_10',
    name: 'Bhaiya Dooj',
    nameHi: 'भैया दूज',
    englishName: 'Bhaiya Dooj',
    hindiName: 'भैया दूज',
    date: '2026-11-10',
    year: 2026,
    month: 11,
    day: 10,
    dayOfWeek: 'Tuesday',
    dayOfWeekHi: 'मंगलवार',
    dateStrEn: 'November 10, 2026, Tuesday',
    dateStrHi: 'नवंबर 10, 2026, मंगलवार',
    tithi: 'Kartika, Shukla Dwitiya',
    tithiHi: 'कार्तिक, शुक्ल द्वितीया',
    description: 'Kartika, Shukla Dwitiya',
    descriptionHi: 'कार्तिक, शुक्ल द्वितीया',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/festivals/bhai-dooj/bhai-dooj-date-time.html?year=2026',
  },
  {
    id: 'chhath_puja_2026_11_15',
    name: 'Chhath Puja',
    nameHi: 'छठ पूजा',
    englishName: 'Chhath Puja',
    hindiName: 'छठ पूजा',
    date: '2026-11-15',
    year: 2026,
    month: 11,
    day: 15,
    dayOfWeek: 'Sunday',
    dayOfWeekHi: 'रविवार',
    dateStrEn: 'November 15, 2026, Sunday',
    dateStrHi: 'नवंबर 15, 2026, रविवार',
    tithi: 'Kartika, Shukla Shashthi',
    tithiHi: 'कार्तिक, शुक्ल षष्ठी',
    description: 'Kartika, Shukla Shashthi',
    descriptionHi: 'कार्तिक, शुक्ल षष्ठी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/festivals/chhath-puja/chhath-puja-date-time.html?year=2026',
  },

  {
    id: 'devutthana_ekadashi_2026_11_20',
    name: 'Devutthana Ekadashi',
    nameHi: 'देवउठनी एकादशी',
    englishName: 'Devutthana Ekadashi',
    hindiName: 'देवउठनी एकादशी',
    date: '2026-11-20',
    year: 2026,
    month: 11,
    day: 20,
    dayOfWeek: 'Friday',
    dayOfWeekHi: 'शुक्रवार',
    dateStrEn: 'November 20, 2026, Friday',
    dateStrHi: 'नवंबर 20, 2026, शुक्रवार',
    tithi: 'Kartika, Shukla Ekadashi',
    tithiHi: 'कार्तिक, शुक्ल एकादशी',
    description: 'Kartika, Shukla Ekadashi',
    descriptionHi: 'कार्तिक, शुक्ल एकादशी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/ekadashis/prabodhini/prabodhini-ekadashi-date-time.html?year=2026',
  },

  {
    id: 'utpanna_ekadashi_2026_12_04',
    name: 'Utpanna Ekadashi',
    nameHi: 'उत्पन्ना एकादशी',
    englishName: 'Utpanna Ekadashi',
    hindiName: 'उत्पन्ना एकादशी',
    date: '2026-12-04',
    year: 2026,
    month: 12,
    day: 4,
    dayOfWeek: 'Friday',
    dayOfWeekHi: 'शुक्रवार',
    dateStrEn: 'December 4, 2026, Friday',
    dateStrHi: 'दिसंबर 4, 2026, शुक्रवार',
    tithi: 'Margashirsha, Krishna Ekadashi',
    tithiHi: 'मार्गशीर्ष, कृष्ण एकादशी',
    description: 'Margashirsha, Krishna Ekadashi',
    descriptionHi: 'मार्गशीर्ष, कृष्ण एकादशी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/ekadashis/utpanna/utpanna-ekadashi-date-time.html?year=2026',
  },

  {
    id: 'mokshada_ekadashi_2026_12_19',
    name: 'Mokshada Ekadashi',
    nameHi: 'मोक्षदा एकादशी',
    englishName: 'Mokshada Ekadashi',
    hindiName: 'मोक्षदा एकादशी',
    date: '2026-12-19',
    year: 2026,
    month: 12,
    day: 19,
    dayOfWeek: 'Saturday',
    dayOfWeekHi: 'शनिवार',
    dateStrEn: 'December 19, 2026, Saturday',
    dateStrHi: 'दिसंबर 19, 2026, शनिवार',
    tithi: 'Margashirsha, Shukla Ekadashi',
    tithiHi: 'मार्गशीर्ष, शुक्ल एकादशी',
    description: 'Margashirsha, Shukla Ekadashi',
    descriptionHi: 'मार्गशीर्ष, शुक्ल एकादशी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/ekadashis/mokshada/mokshada-ekadashi-date-time.html?year=2026',
  },
  {
    id: 'gauna_mokshada_ekadashi_2026_12_20',
    name: 'Gauna Mokshada Ekadashi',
    nameHi: 'गौण मोक्षदा एकादशी',
    englishName: 'Gauna Mokshada Ekadashi',
    hindiName: 'गौण मोक्षदा एकादशी',
    date: '2026-12-20',
    year: 2026,
    month: 12,
    day: 20,
    dayOfWeek: 'Sunday',
    dayOfWeekHi: 'रविवार',
    dateStrEn: 'December 20, 2026, Sunday',
    dateStrHi: 'दिसंबर 20, 2026, रविवार',
    tithi: 'Margashirsha, Shukla Ekadashi',
    tithiHi: 'मार्गशीर्ष, शुक्ल एकादशी',
    description: 'Margashirsha, Shukla Ekadashi',
    descriptionHi: 'मार्गशीर्ष, शुक्ल एकादशी',
    category: 'Hindu Festivals & Others',
    categoryHi: 'हिन्दू त्यौहार एवं अन्य',
    imageUrl:
      'https://www.drikpanchang.com/images/festivals/270x180/puja_thali.jpg',
    url: 'https://www.drikpanchang.com/ekadashis/mokshada/mokshada-ekadashi-date-time.html?year=2026',
  },
];

export const CALENDAR_2026_BY_MONTH: CalendarMonth2026[] = MONTH_NAMES.map(
  (m, index) => {
    const monthNum = index + 1;
    return {
      month: monthNum,
      monthName: m.en,
      monthNameHi: m.hi,
      festivals: CALENDAR_2026.filter(f => f.month === monthNum),
    };
  },
);

/**
 * January 2026 festivals - derived from CALENDAR_2026
 */
export const CALENDAR_JANUARY_2026: Festival2026[] =
  CALENDAR_2026_BY_MONTH[0].festivals;

/**
 * Get all festivals for a specific month (1 - 12)
 */
export const getFestivalsForMonth = (month: number): Festival2026[] => {
  const monthData = CALENDAR_2026_BY_MONTH[month - 1];
  return monthData ? monthData.festivals : [];
};

/**
 * Get all festivals occurring on a specific ISO date (YYYY-MM-DD)
 */
export const getFestivalsForDate = (dateStr: string): Festival2026[] => {
  return CALENDAR_2026.filter(f => f.date === dateStr);
};

/**
 * Get a festival by its unique ID
 */
export const getFestivalById = (id: string): Festival2026 | undefined => {
  return CALENDAR_2026.find(f => f.id === id);
};

/**
 * Search festivals by name in English or Hindi
 */
export const searchFestivals = (
  query: string,
  lang: 'en' | 'hi' = 'en',
): Festival2026[] => {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return CALENDAR_2026.filter(f => {
    if (lang === 'hi') {
      return (
        f.nameHi.includes(query) ||
        f.tithiHi.includes(query) ||
        f.name.toLowerCase().includes(q)
      );
    }
    return (
      f.name.toLowerCase().includes(q) ||
      f.tithi.toLowerCase().includes(q) ||
      f.nameHi.includes(query)
    );
  });
};

/**
 * Get localized festival name based on language code ('en' or 'hi')
 */
export const getLocalizedFestivalName = (
  festival: Festival2026,
  lang: string,
): string => {
  return lang.startsWith('hi')
    ? festival.nameHi || festival.name
    : festival.name;
};

/**
 * Get localized festival date string based on language code ('en' or 'hi')
 */
export const getLocalizedDateStr = (
  festival: Festival2026,
  lang: string,
): string => {
  return lang.startsWith('hi')
    ? festival.dateStrHi || festival.dateStrEn
    : festival.dateStrEn;
};

/**
 * Get localized festival tithi based on language code ('en' or 'hi')
 */
export const getLocalizedTithi = (
  festival: Festival2026,
  lang: string,
): string => {
  return lang.startsWith('hi')
    ? festival.tithiHi || festival.tithi
    : festival.tithi;
};

/**
 * Get localized category based on language code ('en' or 'hi')
 */
export const getLocalizedCategory = (
  festival: Festival2026,
  lang: string,
): string => {
  return lang.startsWith('hi')
    ? festival.categoryHi || festival.category
    : festival.category;
};

export default CALENDAR_2026;
