import imagePath from '@assets/index';

export interface TempleItem {
  id: string;
  nameHi: string;
  nameEn: string;
  locationHi: string;
  locationEn: string;
  stateHi: string;
  stateEn: string;
  deityHi: string;
  deityEn: string;
  image: any;
  category: 'chardham' | 'jyotirlinga' | 'major' | 'shaktipeeth';
  significanceHi: string;
  significanceEn: string;
  timingHi: string;
  timingEn: string;
  descriptionHi: string;
  descriptionEn: string;
}

export const templesData: TempleItem[] = [
  {
    id: 'ram_mandir_ayodhya',
    nameHi: 'श्री राम जन्मभूमि मंदिर',
    nameEn: 'Shri Ram Janmabhoomi Mandir',
    locationHi: 'अयोध्या, उत्तर प्रदेश',
    locationEn: 'Ayodhya, Uttar Pradesh',
    stateHi: 'उत्तर प्रदेश',
    stateEn: 'Uttar Pradesh',
    deityHi: 'भगवान श्री राम (राम लला)',
    deityEn: 'Lord Rama (Ram Lalla)',
    image: imagePath.Rama,
    category: 'major',
    significanceHi: 'भगवान श्री राम की जन्मस्थली एवं विश्वभर के सनातनियों का परम पावन आस्था केंद्र।',
    significanceEn: 'The sacred birthplace of Lord Shri Rama and a premier global spiritual pilgrimage.',
    timingHi: 'प्रातः 06:30 से दोपहर 12:00, सायं 02:00 से रात्रि 10:00',
    timingEn: '06:30 AM – 12:00 PM, 02:00 PM – 10:00 PM',
    descriptionHi: 'अयोध्या में सरयू नदी के तट पर स्थित भव्य श्री राम जन्मभूमि मंदिर भारतीय संस्कृति और आस्था का अनुपम प्रतीक है।',
    descriptionEn: 'Located on the banks of the sacred Saryu river in Ayodhya, this grand temple stands as an epitome of devotion and heritage.',
  },
  {
    id: 'kashi_vishwanath',
    nameHi: 'काशी विश्वनाथ मंदिर',
    nameEn: 'Kashi Vishwanath Temple',
    locationHi: 'वाराणसी, उत्तर प्रदेश',
    locationEn: 'Varanasi, Uttar Pradesh',
    stateHi: 'उत्तर प्रदेश',
    stateEn: 'Uttar Pradesh',
    deityHi: 'भगवान शिव (विश्वेश्वर)',
    deityEn: 'Lord Shiva (Vishwareshwar)',
    image: imagePath.Bholenath,
    category: 'jyotirlinga',
    significanceHi: 'द्वादश ज्योतिर्लिंगों में प्रमुख ज्योतिर्लिंग, जहाँ दर्शन मात्र से मोक्ष प्राप्त होता है।',
    significanceEn: 'One of the most revered 12 Jyotirlingas, believed to grant liberation (Moksha) upon darshan.',
    timingHi: 'प्रातः 03:00 से रात्रि 11:00 (मंगला आरती प्रातः 03:00)',
    timingEn: '03:00 AM – 11:00 PM (Mangala Aarti 03:00 AM)',
    descriptionHi: 'पवित्र गंगा नदी के तट पर स्थित बाबा विश्वनाथ का पावन धाम अनादि काल से आध्यात्मिक चेतना का केंद्र है।',
    descriptionEn: 'Situated on the banks of the holy Ganges, this ancient sanctum has been the core of Indian spirituality since eternity.',
  },
  {
    id: 'kedarnath_dham',
    nameHi: 'केदारनाथ धाम',
    nameEn: 'Kedarnath Dham',
    locationHi: 'रुद्रप्रयाग, उत्तराखण्ड',
    locationEn: 'Rudraprayag, Uttarakhand',
    stateHi: 'उत्तराखण्ड',
    stateEn: 'Uttarakhand',
    deityHi: 'भगवान शिव (केदारनाथ)',
    deityEn: 'Lord Shiva (Kedarnath)',
    image: imagePath.Bholenath,
    category: 'chardham',
    significanceHi: 'चार धाम व द्वादश ज्योतिर्लिंगों में सबसे ऊँचा पावन तीर्थ, पंच केदार में प्रमुख।',
    significanceEn: 'The highest among the 12 Jyotirlingas, part of the holy Char Dham in the mighty Himalayas.',
    timingHi: 'प्रातः 05:00 से दोपहर 01:30, सायं 05:00 से रात्रि 09:00 (ग्रीष्मकालीन)',
    timingEn: '05:00 AM – 01:30 PM, 05:00 PM – 09:00 PM (Seasonal)',
    descriptionHi: 'हिमालय की गगनचुंबी बर्फीली चोटियों के मध्य मंदाकिनी नदी के उद्गम के समीप स्थित अलौकिक धाम।',
    descriptionEn: 'Nestled amidst snow-capped Himalayan peaks near the Mandakini river, this shrine radiates divine serenity.',
  },
  {
    id: 'badrinath_dham',
    nameHi: 'बद्रीनाथ धाम',
    nameEn: 'Badrinath Dham',
    locationHi: 'चमोली, उत्तराखण्ड',
    locationEn: 'Chamoli, Uttarakhand',
    stateHi: 'उत्तराखण्ड',
    stateEn: 'Uttarakhand',
    deityHi: 'भगवान विष्णु (बद्रीनारायण)',
    deityEn: 'Lord Vishnu (Badrinarayan)',
    image: imagePath.Vishnu,
    category: 'chardham',
    significanceHi: 'भारत के चार मुख्य धामों में से एक, जहाँ भगवान विष्णु बद्री (बेर) के वन में ध्यानमग्न हैं।',
    significanceEn: 'One of the four prime Char Dhams of India where Lord Vishnu is enshrined in meditative posture.',
    timingHi: 'प्रातः 04:30 से दोपहर 01:00, सायं 04:00 से रात्रि 09:00',
    timingEn: '04:30 AM – 01:00 PM, 04:00 PM – 09:00 PM',
    descriptionHi: 'अलकनंदा नदी के तट पर नर-नारायण पर्वतों के बीच स्थित यह पावन धाम वैकुंठ का साक्षात स्वरूप माना जाता है।',
    descriptionEn: 'Located along the Alaknanda river between Nar and Narayana mountain ranges, considered an earthly Vaikuntha.',
  },
  {
    id: 'somnath_mandir',
    nameHi: 'सोमनाथ ज्योतिर्लिंग',
    nameEn: 'Somnath Jyotirlinga',
    locationHi: 'प्रभास पाटन, गुजरात',
    locationEn: 'Prabhas Patan, Gujarat',
    stateHi: 'गुजरात',
    stateEn: 'Gujarat',
    deityHi: 'भगवान शिव (सोमनाथ)',
    deityEn: 'Lord Shiva (Somnath)',
    image: imagePath.Bholenath,
    category: 'jyotirlinga',
    significanceHi: 'भारत का प्रथम ज्योतिर्लिंग, जिसका निर्माण स्वयं चंद्रदेव द्वारा कराया गया था।',
    significanceEn: 'The first among the 12 Jyotirlingas, revered as the eternal shrine constructed by Chandra Deva.',
    timingHi: 'प्रातः 06:00 से रात्रि 10:00 (आरती प्रातः 07:00, दोपहर 12:00, सायं 07:00)',
    timingEn: '06:00 AM – 10:00 PM (Aartis at 07:00 AM, 12:00 PM, 07:00 PM)',
    descriptionHi: 'अरब सागर के तट पर स्थित यह भव्य मंदिर भारतीय संस्कृति के अटूट आत्मबल और भक्ति का अमर प्रतीक है।',
    descriptionEn: 'Overlooking the vast Arabian Sea, Somnath stands as an immortal symbol of Indian faith and resilience.',
  },
  {
    id: 'mahakaleshwar_ujjain',
    nameHi: 'महाकालेश्वर मंदिर',
    nameEn: 'Mahakaleshwar Jyotirlinga',
    locationHi: 'उज्जैन, मध्य प्रदेश',
    locationEn: 'Ujjain, Madhya Pradesh',
    stateHi: 'मध्य प्रदेश',
    stateEn: 'Madhya Pradesh',
    deityHi: 'भगवान शिव (महाकाल)',
    deityEn: 'Lord Shiva (Mahakal)',
    image: imagePath.Bholenath,
    category: 'jyotirlinga',
    significanceHi: 'एकमात्र दक्षिणमुखी ज्योतिर्लिंग, जहाँ प्रतिदिन ब्रह्ममुहूर्त में दिव्य भस्म आरती होती है।',
    significanceEn: 'The only south-facing Jyotirlinga, world-famous for its sacred early morning Bhasma Aarti.',
    timingHi: 'प्रातः 04:00 से रात्रि 11:00 (भस्म आरती प्रातः 04:00)',
    timingEn: '04:00 AM – 11:00 PM (Bhasma Aarti at 04:00 AM)',
    descriptionHi: 'पवित्र क्षिप्रा नदी के तट पर स्थित अवंतिका नगरी में काल के स्वामी भगवान महाकाल का दिव्य दरबार।',
    descriptionEn: 'Situated in the ancient holy city of Ujjain along the Shipra river, presiding over time and mortality.',
  },
  {
    id: 'tirupati_balaji',
    nameHi: 'तिरुपति बालाजी (वेंकटेश्वर मंदिर)',
    nameEn: 'Tirupati Balaji (Venkateswara Temple)',
    locationHi: 'तिरुमाला, आन्ध्र प्रदेश',
    locationEn: 'Tirumala, Andhra Pradesh',
    stateHi: 'आन्ध्र प्रदेश',
    stateEn: 'Andhra Pradesh',
    deityHi: 'भगवान वेंकटेश्वर (बालाजी/श्रीनिवास)',
    deityEn: 'Lord Venkateswara (Balaji/Srinivasa)',
    image: imagePath.Vishnu,
    category: 'major',
    significanceHi: 'कलियुग में प्रत्यक्ष फल देने वाले भगवान वेंकटेश्वर का विश्व प्रसिद्ध पावन तीर्थ।',
    significanceEn: 'One of the most visited and revered Vaishnavite shrines globally, known as the abode of Kaliyuga Varada.',
    timingHi: 'प्रातः 03:00 से रात्रि 01:30 (सार्वजनिक दर्शन समय अनुसार)',
    timingEn: '03:00 AM – 01:30 AM (Subject to darshan slots)',
    descriptionHi: 'सप्तगिरि (सात पहाड़ियों) पर स्थित यह भव्य मंदिर अद्वितीय वास्तुकला और असीम भक्ति का केंद्र है।',
    descriptionEn: 'Perched on the Seshachalam hills in Tirumala, this temple represents profound bhakti and heritage.',
  },
  {
    id: 'jagannath_puri',
    nameHi: 'श्री जगन्नाथ मंदिर',
    nameEn: 'Shri Jagannath Temple',
    locationHi: 'पुरी, ओडिशा',
    locationEn: 'Puri, Odisha',
    stateHi: 'ओडिशा',
    stateEn: 'Odisha',
    deityHi: 'भगवान जगन्नाथ, बलभद्र व सुभद्रा',
    deityEn: 'Lord Jagannath, Balabhadra & Subhadra',
    image: imagePath.JagannathRath,
    category: 'chardham',
    significanceHi: 'चार धामों में प्रमुख, विश्वविख्यात वार्षिक रथयात्रा एवं महाप्रसाद का पावन धाम।',
    significanceEn: 'One of the four sacred Char Dhams, globally celebrated for the grand annual Ratha Yatra and Mahaprasad.',
    timingHi: 'प्रातः 05:30 से रात्रि 11:00',
    timingEn: '05:30 AM – 11:00 PM',
    descriptionHi: 'नीलाचल पर्वत पर स्थित यह मंदिर भगवान जगन्नाथ की अगाध लीलाओं और भक्ति का केंद्र है।',
    descriptionEn: 'Overlooking the eastern coast in Puri, this ancient sanctum celebrates the universal love of Lord Jagannath.',
  },
  {
    id: 'meenakshi_amman',
    nameHi: 'मीनाक्षी अम्मन मंदिर',
    nameEn: 'Meenakshi Amman Temple',
    locationHi: 'मदुरै, तमिलनाडु',
    locationEn: 'Madurai, Tamil Nadu',
    stateHi: 'तमिलनाडु',
    stateEn: 'Tamil Nadu',
    deityHi: 'देवी मीनाक्षी (पार्वती) व सुंदरेश्वर (शिव)',
    deityEn: 'Goddess Meenakshi & Sundareswarar',
    image: imagePath.Durga,
    category: 'shaktipeeth',
    significanceHi: 'द्रविड़ वास्तुकला का अनुपम चमत्कार, भव्य गोपुरम और 1000 स्तंभों का अलौकिक मंडप।',
    significanceEn: 'A masterpiece of Dravidian architecture with towering sculptured gopurams and the famous Hall of 1000 Pillars.',
    timingHi: 'प्रातः 05:00 से दोपहर 12:30, सायं 04:00 से रात्रि 10:00',
    timingEn: '05:00 AM – 12:30 PM, 04:00 PM – 10:00 PM',
    descriptionHi: 'वैगई नदी के तट पर स्थित मदुरै का यह ऐतिहासिक मंदिर देवी शक्ति और भगवान शिव के पावन विवाह का साक्षी है।',
    descriptionEn: 'A historic temple on the banks of Vaigai river celebrating the divine union of Goddess Meenakshi and Lord Shiva.',
  },
  {
    id: 'vaishno_devi',
    nameHi: 'माँ वैष्णो देवी धाम',
    nameEn: 'Maa Vaishno Devi Dham',
    locationHi: 'कटरा, जम्मू और कश्मीर',
    locationEn: 'Katra, Jammu & Kashmir',
    stateHi: 'जम्मू और कश्मीर',
    stateEn: 'Jammu & Kashmir',
    deityHi: 'माँ वैष्णो देवी (महाकाली, महालक्ष्मी, महासरस्वती)',
    deityEn: 'Maa Vaishno Devi (Mahakali, Mahalakshmi, Mahasaraswati)',
    image: imagePath.Durga,
    category: 'shaktipeeth',
    significanceHi: 'त्रिकूटा पर्वत की पवित्र गुफा में तीन प्राकृतिक पिंडी स्वरूपों का पावन संगम।',
    significanceEn: 'The revered mountain cave shrine on Trikuta hills enshrining the three holy natural Pindis.',
    timingHi: '24 घंटे खुला रहता है (दैनिक आरती समय: प्रातः 06:00, सायं 07:00)',
    timingEn: 'Open 24 Hours (Daily Aarti: 06:00 AM & 07:00 PM)',
    descriptionHi: 'भक्तों की मनोकामना पूर्ण करने वाली माँ वैष्णो देवी का त्रिकूट पर्वत पर स्थित पावन धाम।',
    descriptionEn: 'Millions of pilgrims trek each year to seek the divine blessings of Mother Vaishno Devi.',
  },
  {
    id: 'siddhivinayak_mumbai',
    nameHi: 'श्री सिद्धिविनायक मंदिर',
    nameEn: 'Shri Siddhivinayak Temple',
    locationHi: 'प्रभादेवी, मुंबई, महाराष्ट्र',
    locationEn: 'Prabhadevi, Mumbai, Maharashtra',
    stateHi: 'महाराष्ट्र',
    stateEn: 'Maharashtra',
    deityHi: 'भगवान श्री गणेश (सिद्धिविनायक)',
    deityEn: 'Lord Ganesha (Siddhivinayak)',
    image: imagePath.Ganesha,
    category: 'major',
    significanceHi: 'मनोकामना पूर्ण करने वाले सिद्धिविनायक गणपति, जिनकी सूंड दाहिनी ओर मुड़ी है।',
    significanceEn: 'A globally renowned Ganesha temple with right-turned trunk (Siddhi Vinayaka), fulfilling desires of all seekers.',
    timingHi: 'प्रातः 05:30 से रात्रि 10:00 (मंगलवार विशेष दर्शन)',
    timingEn: '05:30 AM – 10:00 PM (Special Tuesday Darshan)',
    descriptionHi: 'मुंबई के केंद्र में स्थित यह मंदिर सभी शुभ कार्यों में विघ्नहर्ता गणेश जी की कृपा प्राप्ति का पावन स्थल है।',
    descriptionEn: 'Located in Mumbai, devotees throng here to seek obstacles-free success and blessings from Lord Ganesha.',
  },
  {
    id: 'kamakhya_temple',
    nameHi: 'कामाख्या देवी मंदिर',
    nameEn: 'Kamakhya Temple',
    locationHi: 'गुवाहाटी, असम',
    locationEn: 'Guwahati, Assam',
    stateHi: 'असम',
    stateEn: 'Assam',
    deityHi: 'माँ कामाख्या (शक्तिपीठ)',
    deityEn: 'Maa Kamakhya (Shakti Peeth)',
    image: imagePath.Durga,
    category: 'shaktipeeth',
    significanceHi: '51 शक्तिपीठों में सर्वोच्च तांत्रिक शक्तिपीठ, अम्बुबाची मेले के लिए प्रसिद्ध।',
    significanceEn: 'The supreme center of Tantric Shaktism among the 51 Shakti Peethas, famous for the Ambubachi Mela.',
    timingHi: 'प्रातः 05:30 से दोपहर 01:00, सायं 02:30 से सायं 05:30',
    timingEn: '05:30 AM – 01:00 PM, 02:30 PM – 05:30 PM',
    descriptionHi: 'नीलांचल पर्वत पर स्थित यह रहस्यमयी और जागृत शक्तिपीठ संपूर्ण सृष्टि की जननी देवी कामाख्या को समर्पित है।',
    descriptionEn: 'Situated on the Nilachal hill in Guwahati, revered as the ultimate source of cosmic creation and divine Shakti.',
  },
];
