export interface Festival {
  id: string;
  englishName: string;
  hindiName: string;
  month: number; // 1-12
  day: number;
  dateStrEn: string;
  dateStrHi: string;
  deity: string[];
  category: string;
  tithi: string;
  description: string;
  regions: string[];
}

export const festivalData: Festival[] = [
  {
    id: 'lohri',
    englishName: 'Lohri',
    hindiName: 'लोहड़ी',
    month: 1,
    day: 13,
    dateStrEn: 'Jan 13',
    dateStrHi: '13 जनवरी',
    deity: ['Surya', 'Agni'],
    category: 'Regional Festival',
    tithi: 'Around Magha Sankranti',
    description:
      'A winter harvest festival traditionally celebrated with bonfires.',
    regions: ['Punjab'],
  },
  {
    id: 'makar_sankranti',
    englishName: 'Makar Sankranti',
    hindiName: 'मकर संक्रांति',
    month: 1,
    day: 14,
    dateStrEn: 'Jan 14',
    dateStrHi: '14 जनवरी',
    deity: ['Surya'],
    category: 'Sankranti',
    tithi: 'Solar transition into Makara',
    description:
      "A solar festival marking the Sun's transition into Capricorn.",
    regions: ['Pan-India'],
  },
  {
    id: 'vasant_panchami',
    englishName: 'Vasant Panchami',
    hindiName: 'वसंत पंचमी',
    month: 1,
    day: 23,
    dateStrEn: 'Jan 23',
    dateStrHi: '23 जनवरी',
    deity: ['Saraswati'],
    category: 'Deity Festival',
    tithi: 'Magha Shukla Panchami',
    description:
      'A festival welcoming spring and honoring Goddess Saraswati, associated with knowledge, music and learning.',
    regions: [
      'Pan-India',
      'West Bengal',
      'Bihar',
      'Odisha',
      'Uttar Pradesh',
      'Rajasthan',
    ],
  },
  {
    id: 'ratha_saptami',
    englishName: 'Ratha Saptami',
    hindiName: 'रथ सप्तमी',
    month: 1,
    day: 25,
    dateStrEn: 'Jan 25',
    dateStrHi: '25 जनवरी',
    deity: ['Surya'],
    category: 'Deity Festival',
    tithi: 'Magha Shukla Saptami',
    description:
      "A festival dedicated to Surya representing the Sun God's chariot turning toward the northern direction.",
    regions: [
      'Pan-India',
      'Andhra Pradesh',
      'Telangana',
      'Karnataka',
      'Tamil Nadu',
    ],
  },
  {
    id: 'maha_shivratri',
    englishName: 'Maha Shivratri',
    hindiName: 'महाशिवरात्रि',
    month: 2,
    day: 15,
    dateStrEn: 'Feb 15',
    dateStrHi: '15 फ़रवरी',
    deity: ['Shiva'],
    category: 'Deity Festival',
    tithi: 'Phalguna Krishna Chaturdashi',
    description: 'A major festival dedicated to Lord Shiva.',
    regions: ['Pan-India'],
  },
  {
    id: 'phulera_dooj',
    englishName: 'Phulera Dooj',
    hindiName: 'फुलेरा दूज',
    month: 2,
    day: 19,
    dateStrEn: 'Feb 19',
    dateStrHi: '19 फ़रवरी',
    deity: ['Krishna', 'Radha'],
    category: 'Deity Festival',
    tithi: 'Phalguna Shukla Dwitiya',
    description:
      'A Braj tradition associated with Radha and Krishna and the beginning of Holi celebrations.',
    regions: ['Uttar Pradesh', 'Rajasthan', 'Haryana'],
  },
  {
    id: 'holika_dahan',
    englishName: 'Holika Dahan',
    hindiName: 'होलिका दहन',
    month: 3,
    day: 2,
    dateStrEn: 'Mar 2',
    dateStrHi: '2 मार्च',
    deity: ['Vishnu', 'Prahlada', 'Holika'],
    category: 'Major Festival',
    tithi: 'Phalguna Purnima',
    description:
      "A bonfire ritual commemorating Prahlada's devotion and the defeat of Holika.",
    regions: ['Pan-India'],
  },
  {
    id: 'holi',
    englishName: 'Holi',
    hindiName: 'होली',
    month: 3,
    day: 3,
    dateStrEn: 'Mar 3',
    dateStrHi: '3 मार्च',
    deity: ['Krishna', 'Radha'],
    category: 'Major Festival',
    tithi: 'Phalguna Purnima / following day',
    description:
      'The festival of colors celebrating spring, joy, devotion and the triumph of good over evil.',
    regions: ['Pan-India', 'Nepal'],
  },
  {
    id: 'chaitra_navratri',
    englishName: 'Chaitra Navratri',
    hindiName: 'चैत्र नवरात्रि',
    month: 3,
    day: 19,
    dateStrEn: 'Mar 19',
    dateStrHi: '19 मार्च',
    deity: ['Durga', 'Shakti'],
    category: 'Navratri',
    tithi: 'Chaitra Shukla Pratipada to Navami',
    description:
      'Nine nights dedicated to Goddess Durga and her manifestations, marking the beginning of the Hindu lunar year in many traditions.',
    regions: ['Pan-India', 'North India', 'West India'],
  },
  {
    id: 'rama_navami',
    englishName: 'Rama Navami',
    hindiName: 'राम नवमी',
    month: 3,
    day: 26,
    dateStrEn: 'Mar 26',
    dateStrHi: '26 मार्च',
    deity: ['Rama'],
    category: 'Deity Festival',
    tithi: 'Chaitra Shukla Navami',
    description:
      'Celebrates the birth of Lord Rama, an important figure in the Ramayana.',
    regions: ['Pan-India', 'Nepal'],
  },
  {
    id: 'hanuman_jayanti',
    englishName: 'Hanuman Jayanti',
    hindiName: 'हनुमान जयंती',
    month: 4,
    day: 2,
    dateStrEn: 'Apr 2',
    dateStrHi: '2 अप्रैल',
    deity: ['Hanuman'],
    category: 'Deity Festival',
    tithi: 'Chaitra Purnima',
    description:
      'Celebrates the birth of Lord Hanuman and is marked by prayer, chanting and Hanuman worship.',
    regions: ['Pan-India'],
  },
  {
    id: 'buddha_purnima',
    englishName: 'Buddha Purnima',
    hindiName: 'बुद्ध पूर्णिमा',
    month: 5,
    day: 1,
    dateStrEn: 'May 1',
    dateStrHi: '1 मई',
    deity: ['Buddha'],
    category: 'Religious Observance',
    tithi: 'Vaishakha Purnima',
    description:
      'Commemorates important events associated with Gautama Buddha.',
    regions: ['Pan-India', 'Nepal'],
  },
  {
    id: 'ganga_dussehra',
    englishName: 'Ganga Dussehra',
    hindiName: 'गंगा दशहरा',
    month: 5,
    day: 25,
    dateStrEn: 'May 25',
    dateStrHi: '25 मई',
    deity: ['Ganga'],
    category: 'Deity Festival',
    tithi: 'Jyeshtha Shukla Dashami',
    description: 'Celebrates the descent of the sacred river Ganga to Earth.',
    regions: ['North India', 'Uttar Pradesh', 'Uttarakhand', 'Bihar'],
  },
  {
    id: 'nirjala_ekadashi',
    englishName: 'Nirjala Ekadashi',
    hindiName: 'निर्जला एकादशी',
    month: 6,
    day: 25,
    dateStrEn: 'Jun 25',
    dateStrHi: '25 जून',
    deity: ['Vishnu'],
    category: 'Ekadashi',
    tithi: 'Jyeshtha Shukla Ekadashi',
    description:
      'A particularly strict Ekadashi traditionally associated with fasting and Vishnu devotion.',
    regions: ['Pan-India'],
  },
  {
    id: 'jagannath_rath_yatra',
    englishName: 'Jagannath Rath Yatra',
    hindiName: 'जगन्नाथ रथ यात्रा',
    month: 7,
    day: 16,
    dateStrEn: 'Jul 16',
    dateStrHi: '16 जुलाई',
    deity: ['Jagannath', 'Balabhadra', 'Subhadra'],
    category: 'Deity Festival',
    tithi: 'Ashadha Shukla Dwitiya',
    description:
      'The famous chariot festival of Lord Jagannath and his siblings.',
    regions: ['Odisha', 'West Bengal', 'Gujarat', 'Pan-India'],
  },
  {
    id: 'guru_purnima',
    englishName: 'Guru Purnima',
    hindiName: 'गुरु पूर्णिमा',
    month: 7,
    day: 29,
    dateStrEn: 'Jul 29',
    dateStrHi: '29 जुलाई',
    deity: ['Guru', 'Vyasa'],
    category: 'Religious Observance',
    tithi: 'Ashadha Purnima',
    description:
      'A day dedicated to honoring spiritual teachers and the guru tradition.',
    regions: ['Pan-India', 'Nepal'],
  },
  {
    id: 'nag_panchami',
    englishName: 'Nag Panchami',
    hindiName: 'नाग पंचमी',
    month: 8,
    day: 17,
    dateStrEn: 'Aug 17',
    dateStrHi: '17 अगस्त',
    deity: ['Naga', 'Shiva'],
    category: 'Deity Festival',
    tithi: 'Shravana Shukla Panchami',
    description:
      'A traditional festival honoring serpent deities and seeking protection and blessings.',
    regions: ['Pan-India', 'Nepal'],
  },
  {
    id: 'raksha_bandhan',
    englishName: 'Raksha Bandhan',
    hindiName: 'रक्षाबंधन',
    month: 8,
    day: 28,
    dateStrEn: 'Aug 28',
    dateStrHi: '28 अगस्त',
    deity: ['Krishna', 'Indra'],
    category: 'Major Festival',
    tithi: 'Shravana Purnima',
    description:
      'A festival celebrating the bond of protection and affection between siblings.',
    regions: ['Pan-India', 'Nepal'],
  },
  {
    id: 'janmashtami',
    englishName: 'Janmashtami',
    hindiName: 'कृष्ण जन्माष्टमी',
    month: 9,
    day: 4,
    dateStrEn: 'Sep 4',
    dateStrHi: '4 सितंबर',
    deity: ['Krishna'],
    category: 'Major Festival',
    tithi: 'Bhadrapada Krishna Ashtami',
    description: 'Celebrates the birth of Lord Krishna.',
    regions: ['Pan-India'],
  },
  {
    id: 'ganesh_chaturthi',
    englishName: 'Ganesh Chaturthi',
    hindiName: 'गणेश चतुर्थी',
    month: 9,
    day: 14,
    dateStrEn: 'Sep 14',
    dateStrHi: '14 सितंबर',
    deity: ['Ganesha'],
    category: 'Major Festival',
    tithi: 'Bhadrapada Shukla Chaturthi',
    description: 'Celebrates the birth of Lord Ganesha.',
    regions: ['Maharashtra', 'Karnataka'],
  },
  {
    id: 'gauri_puja',
    englishName: 'Gauri Puja',
    hindiName: 'गौरी पूजा',
    month: 9,
    day: 18,
    dateStrEn: 'Sep 18',
    dateStrHi: '18 सितंबर',
    deity: ['Gauri', 'Parvati'],
    category: 'Deity Festival',
    tithi: 'Varies by regional tradition',
    description: 'A festival honoring Goddess Gauri, a form of Parvati.',
    regions: ['Maharashtra', 'Karnataka', 'Rajasthan', 'Gujarat'],
  },
  {
    id: 'navratri',
    englishName: 'Navratri',
    hindiName: 'शारदीय नवरात्रि',
    month: 10,
    day: 11,
    dateStrEn: 'Oct 11',
    dateStrHi: '11 अक्टूबर',
    deity: ['Durga'],
    category: 'Navratri',
    tithi: 'Ashwin Shukla Pratipada',
    description: 'Nine nights of worship dedicated to Goddess Durga.',
    regions: ['Pan-India'],
  },
  {
    id: 'dussehra',
    englishName: 'Dussehra',
    hindiName: 'दशहरा',
    month: 10,
    day: 20,
    dateStrEn: 'Oct 20',
    dateStrHi: '20 अक्टूबर',
    deity: ['Rama', 'Durga'],
    category: 'Major Festival',
    tithi: 'Ashwin Shukla Dashami',
    description:
      "Celebrates the victory of good over evil and is associated with Rama's victory over Ravana.",
    regions: ['Pan-India'],
  },
  {
    id: 'karwa_chauth',
    englishName: 'Karwa Chauth',
    hindiName: 'करवा चौथ',
    month: 10,
    day: 29,
    dateStrEn: 'Oct 29',
    dateStrHi: '29 अक्टूबर',
    deity: ['Parvati'],
    category: 'Vrat',
    tithi: 'Kartika Krishna Chaturthi',
    description: 'A traditional fasting observance for marital devotion.',
    regions: ['North India'],
  },
  {
    id: 'diwali',
    englishName: 'Diwali',
    hindiName: 'दीपावली',
    month: 11,
    day: 8,
    dateStrEn: 'Nov 8',
    dateStrHi: '8 नवंबर',
    deity: ['Lakshmi', 'Ganesha'],
    category: 'Major Festival',
    tithi: 'Kartika Amavasya',
    description: 'The festival of lights.',
    regions: ['Pan-India'],
  },
  {
    id: 'lakshmi_puja',
    englishName: 'Lakshmi Puja',
    hindiName: 'लक्ष्मी पूजा',
    month: 11,
    day: 8,
    dateStrEn: 'Nov 8',
    dateStrHi: '8 नवंबर',
    deity: ['Lakshmi', 'Ganesha'],
    category: 'Diwali',
    tithi: 'Kartika Amavasya',
    description:
      'A Diwali worship tradition dedicated to Goddess Lakshmi and Lord Ganesha.',
    regions: ['Pan-India'],
  },
  {
    id: 'govardhan_puja',
    englishName: 'Govardhan Puja',
    hindiName: 'गोवर्धन पूजा',
    month: 11,
    day: 10,
    dateStrEn: 'Nov 10',
    dateStrHi: '10 नवंबर',
    deity: ['Krishna', 'Govardhan'],
    category: 'Diwali',
    tithi: 'Kartika Shukla Pratipada',
    description:
      "Celebrates Krishna's protection of the people of Braj through the lifting of Govardhan Hill.",
    regions: ['Uttar Pradesh', 'Rajasthan', 'Madhya Pradesh', 'Gujarat'],
  },
  {
    id: 'bhai_dooj',
    englishName: 'Bhai Dooj',
    hindiName: 'भाई दूज',
    month: 11,
    day: 11,
    dateStrEn: 'Nov 11',
    dateStrHi: '11 नवंबर',
    deity: ['Yama', 'Yamuna'],
    category: 'Diwali',
    tithi: 'Kartika Shukla Dwitiya',
    description:
      'A festival celebrating the bond between brothers and sisters.',
    regions: ['Pan-India', 'Nepal'],
  },
];
