import { StyleSheet } from 'react-native';
import colors from '@theme/colors';
import fonts from '@theme/fonts';
import { fs, scale, verticalScale } from '@theme/sizes';

/** Shared styles used across ProfileScreen and its sub-components. */
const profileStyles = StyleSheet.create({
  safeArea: { flex: 1 },
  // paddingBottom is set dynamically in ProfileScreen via insets.bottom
  scrollContent: { paddingBottom: scale(16), alignItems: 'center' },

  profileCard: { flexDirection: 'row', width: '90%', gap: scale(10) },
  avatarBorder: {
    width: scale(60),
    height: scale(60),
    borderRadius: scale(45),
    borderWidth: scale(3),
    borderColor: colors.ring,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: scale(14),
    backgroundColor: colors.profileEditBgSubtle,
  },
  avatarImage: { width: '90%', height: '90%', borderRadius: scale(40), resizeMode: 'cover' },
  userName: {
    fontSize: fs(18),
    fontFamily: fonts.PoppinsMedium,
    color: colors.secondary,
    flexShrink: 1,
  },
  userJoined: {
    fontSize: fs(11),
    fontFamily: fonts.PoppinsRegular,
    color: colors.accent,
    opacity: 0.8,
    flexShrink: 1,
  },

  sectionCard: {
    width: '95%',
    backgroundColor: colors.white,
    borderRadius: scale(20),
    padding: scale(18),
    marginBottom: scale(16),
    borderWidth: 1,
    borderColor: colors.borderLight,
    shadowColor: colors.ring,
    shadowOffset: { width: 0, height: scale(6) },
    shadowOpacity: 0.04,
    shadowRadius: scale(12),
    elevation: 3,
  },
  sectionTitle: {
    fontSize: fs(14),
    fontFamily: fonts.PoppinsSemiBold,
    color: colors.secondary,
    marginBottom: scale(14),
  },
  separator: { height: 1, backgroundColor: colors.borderSubtle, marginVertical: scale(10) },

  statsGrid: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    width: '100%',
  },
  statItem: { alignItems: 'center', flex: 1 },
  statDivider: { width: 1, height: scale(28), backgroundColor: colors.borderMedium },
  statValue: {
    fontSize: fs(16),
    fontFamily: fonts.PoppinsSemiBold,
    color: colors.ring,
    marginBottom: scale(2),
  },
  statLabel: {
    fontSize: fs(9),
    fontFamily: fonts.PoppinsRegular,
    color: colors.secondary,
    opacity: 0.75,
    textAlign: 'center',
  },

  sectionContainer: { width: '100%', marginVertical: scale(8) },
  rowTitle: {
    fontSize: fs(14),
    fontFamily: fonts.PoppinsSemiBold,
    color: colors.secondary,
    paddingHorizontal: scale(20),
    marginBottom: scale(12),
  },
  favStoriesScroll: { paddingHorizontal: scale(20), paddingBottom: scale(6) },
  storyBookCard: { width: scale(130), marginRight: scale(14) },
  bookCoverContainer: {
    width: '100%',
    height: verticalScale(160),
    borderRadius: scale(12),
    backgroundColor: colors.white,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.borderMedium,
    shadowColor: colors.ring,
    shadowOffset: { width: 0, height: scale(4) },
    shadowOpacity: 0.06,
    shadowRadius: scale(8),
    elevation: 2,
    position: 'relative',
    marginBottom: scale(8),
  },
  bookCoverImage: { width: '100%', height: '100%', resizeMode: 'cover' },
  categoryBadge: {
    position: 'absolute',
    bottom: scale(8),
    left: scale(8),
    backgroundColor: colors.profileEditBgActive,
    borderRadius: scale(10),
    paddingHorizontal: scale(8),
    paddingVertical: scale(2),
  },
  categoryBadgeText: {
    fontSize: fs(8),
    fontFamily: fonts.PoppinsMedium,
    color: colors.white,
    textTransform: 'uppercase',
  },
  storyBookTitle: {
    fontSize: fs(12),
    fontFamily: fonts.PoppinsMedium,
    color: colors.secondary,
    paddingHorizontal: scale(2),
  },
  removeFavoriteBadge: {
    position: 'absolute',
    top: scale(6),
    right: scale(6),
    width: scale(22),
    height: scale(22),
    borderRadius: scale(11),
    backgroundColor: colors.ring,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  removeFavoriteText: {
    color: colors.white,
    fontSize: fs(20),
    fontFamily: fonts.Marcellus,
    lineHeight: fs(15),
    textAlign: 'center',
  },

  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: scale(8),
  },
  settingInfo: { flex: 1, marginRight: scale(10) },
  settingLabel: {
    fontSize: fs(13),
    fontFamily: fonts.PoppinsMedium,
    color: colors.secondary,
    flexShrink: 1,
  },
  settingSubLabel: {
    fontSize: fs(10.5),
    fontFamily: fonts.PoppinsRegular,
    color: colors.mutedForeground,
    marginTop: scale(1),
    flexShrink: 1,
  },
  languageToggleContainer: {
    flexDirection: 'row',
    borderRadius: scale(16),
    backgroundColor: colors.accentLightBg,
    padding: scale(3),
    borderWidth: 1,
    borderColor: colors.accentBorderSubtle,
  },
  langButton: {
    paddingHorizontal: scale(12),
    paddingVertical: scale(6),
    borderRadius: scale(14),
  },
  langButtonActive: { backgroundColor: colors.ring },
  langButtonText: {
    fontSize: fs(11),
    fontFamily: fonts.PoppinsMedium,
    color: colors.secondary,
  },
  langButtonTextActive: { color: colors.white },
  giveUpButton: {
    backgroundColor: colors.dangerSubtle,
    borderWidth: 1,
    borderColor: colors.dangerBorder,
    paddingHorizontal: scale(14),
    paddingVertical: scale(6),
    borderRadius: scale(8),
  },
  giveUpButtonText: {
    color: colors.profileGiveUpText,
    fontSize: fs(11.5),
    fontFamily: fonts.PoppinsMedium,
  },

  dangerZoneCard: {
    borderColor: colors.profileDangerZoneBorder,
    borderWidth: 1,
    marginTop: scale(16),
  },
  resetButton: {
    backgroundColor: colors.dangerSubtle,
    borderWidth: 1,
    borderColor: colors.dangerBorder,
    paddingHorizontal: scale(14),
    paddingVertical: scale(6),
    borderRadius: scale(8),
  },
  resetButtonText: {
    color: colors.danger,
    fontSize: fs(11.5),
    fontFamily: fonts.PoppinsMedium,
  },

  modalCenterContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.overlayBackdrop,
    paddingHorizontal: scale(20),
  },
  modalCard: {
    width: '100%',
    backgroundColor: colors.white,
    borderRadius: scale(20),
    padding: scale(24),
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.borderMedium,
    shadowColor: colors.ring,
    shadowOffset: { width: 0, height: scale(10) },
    shadowOpacity: 0.1,
    shadowRadius: scale(20),
    elevation: 5,
  },
  modalIcon: { fontSize: fs(36), marginBottom: scale(12) },
  modalTitle: {
    fontSize: fs(18),
    fontFamily: fonts.Marcellus,
    color: colors.secondary,
    marginBottom: scale(8),
    textAlign: 'center',
  },
  modalMessage: {
    fontSize: fs(12),
    fontFamily: fonts.PoppinsRegular,
    color: colors.mutedForeground,
    textAlign: 'center',
    lineHeight: fs(18),
    marginBottom: scale(20),
  },
  modalButton: {
    backgroundColor: colors.ring,
    paddingHorizontal: scale(28),
    paddingVertical: scale(10),
    borderRadius: scale(12),
    width: '100%',
    alignItems: 'center',
  },
  modalButtonText: {
    color: colors.white,
    fontSize: fs(13),
    fontFamily: fonts.PoppinsMedium,
  },
  modalCloseBtn: {
    position: 'absolute',
    top: scale(14),
    right: scale(14),
    zIndex: 10,
    padding: scale(4),
  },
  modalCloseBtnText: {
    fontSize: fs(14),
    color: colors.mutedForeground,
    fontFamily: fonts.PoppinsRegular,
  },

  modalTitleDestructive: {
    fontSize: fs(18),
    fontFamily: fonts.Marcellus,
    color: colors.danger,
    marginBottom: scale(8),
    textAlign: 'center',
  },
  modalDescription: {
    fontSize: fs(12),
    fontFamily: fonts.PoppinsRegular,
    color: colors.mutedForeground,
    textAlign: 'center',
    lineHeight: fs(17),
    marginBottom: scale(16),
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: scale(6),
    alignSelf: 'stretch',
  },
  checkbox: {
    width: scale(18),
    height: scale(18),
    borderRadius: scale(4),
    borderWidth: 1.5,
    borderColor: colors.mutedForeground,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: scale(8),
    flexShrink: 0,
  },
  checkboxActive: { borderColor: colors.danger, backgroundColor: colors.dangerSubtle },
  checkboxTick: { color: colors.danger, fontSize: fs(11), fontWeight: 'bold' },
  checkboxLabel: {
    flex: 1,
    fontSize: fs(11),
    fontFamily: fonts.PoppinsRegular,
    color: colors.secondary,
  },
  resetConfirmLabel: {
    fontSize: fs(11.5),
    fontFamily: fonts.PoppinsMedium,
    color: colors.secondary,
    alignSelf: 'flex-start',
    marginTop: scale(14),
    marginBottom: scale(6),
  },
  resetTextInput: {
    width: '100%',
    height: scale(38),
    borderWidth: 1,
    borderColor: colors.borderStrong,
    borderRadius: scale(8),
    backgroundColor: colors.white,
    paddingHorizontal: scale(10),
    color: colors.danger,
    fontFamily: fonts.PoppinsSemiBold,
    fontSize: fs(13),
    textAlign: 'center',
  },
  resetActionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: scale(16),
  },
  resetCancelBtn: {
    flex: 1,
    marginRight: scale(6),
    height: scale(38),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: scale(8),
    borderWidth: 1,
    borderColor: colors.borderStrong,
  },
  resetCancelText: {
    color: colors.secondary,
    fontFamily: fonts.PoppinsMedium,
    fontSize: fs(12),
  },
  resetConfirmBtn: {
    flex: 1,
    marginLeft: scale(6),
    height: scale(38),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: scale(8),
    backgroundColor: colors.danger,
  },
  resetConfirmBtnDisabled: { backgroundColor: colors.neutralDisabled, opacity: 0.4 },
  resetConfirmText: {
    color: colors.white,
    fontFamily: fonts.PoppinsMedium,
    fontSize: fs(12),
  },
});

export default profileStyles;
