const imagePath = {
  greeting: require('./png/greeting.webp'),
  Bholenath: require('./png/Bhole.webp'),
  Brahma: require('./png/Bramaji.webp'),
  Durga: require('./png/Durgama.webp'),
  Ganesha: require('./png/Ganesha.webp'),
  Hanuman: require('./png/Hunumanji.webp'),
  Krishna: require('./png/Krishan.webp'),
  Laxmi: require('./png/Laxmima.webp'),
  Rama: require('./png/Ramji.webp'),
  Saraswati: require('./png/Saraswatima.webp'),
  Surya: require('./png/Suryadev.webp'),
  Vishnu: require('./png/Vishnu1.webp'),
  Kubera: require('./png/Kubera.webp'),
  ShaniDev: require('./png/ShaniDev.webp'),
  SriRadha: require('./png/Radhaji.webp'),
  dhahiHande: require('./png/dhahiHande.webp'),
  nagpachmi: require('./png/nagpachmi.webp'),
  BhaiDhuj: require('./png/BhaiDhuj.webp'),
  BhaiDooj: require('./png/BhaiDhuj.webp'),
  Dashera: require('./png/Dashera.webp'),
  Dussehra: require('./png/Dashera.webp'),
  GaneshChturdi: require('./png/GaneshChturdi.webp'),
  GaneshChaturthi: require('./png/GaneshChturdi.webp'),
  GoverDhan: require('./png/GoverDhan.webp'),
  Govardhan: require('./png/GoverDhan.webp'),
  Karwachauth: require('./png/Karwachauth.webp'),
  KarwaChauth: require('./png/Karwachauth.webp'),
  Navratri: require('./png/Navratri.webp'),
  RakhiBandan: require('./png/RakhiBandan.webp'),
  RakshaBandhan: require('./png/RakhiBandan.webp'),
  compressedVishnu: require('./png/Vishnu1.webp'),
  OnBoarding: [
    require('./png/OnBoarding1.webp'),
    require('./png/OnBoarding2.webp'),
    require('./png/OnBoarding3.webp'),
  ],
  bhaktiVideo: require('./video/bhakti.mp4'),
  MalaMoti: require('./png/MalaMoti.webp'),
  Diwali: require('./png/Diwali.webp'),
  Goripuja: require('./png/Goripuja.webp'),
  GauriPuja: require('./png/Goripuja.webp'),
  HoliDehan: require('./png/HoliDehan.webp'),
  HoliDahan: require('./png/HoliDehan.webp'),
  HoliRang: require('./png/HoliRang.webp'),
  Holi: require('./png/HoliRang.webp'),
  JagannathRath: require('./png/JagannathRath.webp'),
  JagannathRathYatra: require('./png/JagannathRath.webp'),
  Shivratri: require('./png/Shivratri.webp'),
  MahaShivratri: require('./png/Shivratri.webp'),
  VasantPanchami: require('./png/VasantPanchami.webp'),
  user: require('./png/user.webp'),
  profile: require('./png/user.webp'),
  pencil: require('./png/pencil.webp'),
};

export default imagePath;
