import Back from './svg/Back.svg';
import Forward from './svg/Forward.svg';
import Bell from './svg/bell.svg';
import Pin from './svg/Pin.svg';
import FoldedHands from './svg/foldedhands.svg';
import Location from './svg/location.svg';
import Tag from './svg/tag.svg';

const imagePath = {
  Back,
  Forward,
  greeting: require('./png/greeting.webp'),
  lotus: require('./png/lotus.webp'),
  Bholenath: require('./png/Bhole.webp'),
  Brahma: require('./png/Bramaji.webp'),
  Durga: require('./png/Durgama.webp'),
  Ganesha: require('./png/Ganesha.webp'),
  Hanuman: require('./png/Hunumanji.webp'),
  Krishna: require('./png/Krishan.webp'),
  Laxmi: require('./png/Laxmima.webp'),
  Rama: require('./png/Ramji.webp'),
  Saraswati: require('./png/Saraswatima.webp'),
  Surya: require('./png/Suryadev.webp'),
  Vishnu: require('./png/Vishnu1.webp'),
  Kubera: require('./png/Kubera.webp'),
  ShaniDev: require('./png/ShaniDev.webp'),
  SriRadha: require('./png/Radhaji.webp'),
  dhahiHande: require('./png/dhahiHande.webp'),
  nagpachmi: require('./png/nagpachmi.webp'),
  BhaiDhuj: require('./png/BhaiDhuj.webp'),
  BhaiDooj: require('./png/BhaiDhuj.webp'),
  Dashera: require('./png/Dashera.webp'),
  Dussehra: require('./png/Dashera.webp'),
  GaneshChturdi: require('./png/GaneshChturdi.webp'),
  Ganga: require('./png/Ganga.webp'),
  Gangama: require('./png/Ganga.webp'),
  GangaMaa: require('./png/Ganga.webp'),
  GaneshChaturthi: require('./png/GaneshChturdi.webp'),
  GoverDhan: require('./png/GoverDhan.webp'),
  Govardhan: require('./png/GoverDhan.webp'),
  Karwachauth: require('./png/Karwachauth.webp'),
  Kali: require('./png/Kalimaa.webp'),
  Kalima: require('./png/Kalimaa.webp'),
  Kalimaa: require('./png/Kalimaa.webp'),
  KaliMaa: require('./png/Kalimaa.webp'),
  KarwaChauth: require('./png/Karwachauth.webp'),
  Navratri: require('./png/Navratri.webp'),
  RakhiBandan: require('./png/RakhiBandan.webp'),
  RakshaBandhan: require('./png/RakhiBandan.webp'),
  compressedVishnu: require('./png/Vishnu1.webp'),
  Vishwakarma: require('./png/viswa.webp'),
  Viswakarma: require('./png/viswa.webp'),
  OnBoarding: [
    require('./png/OnBoarding1.webp'),
    require('./png/OnBoarding2.webp'),
    require('./png/OnBoarding3.webp'),
  ],
  bhaktiVideo: require('./video/bhakti.mp4'),
  MalaMoti: require('./png/MalaMoti.webp'),
  Diwali: require('./png/Diwali.webp'),
  Goripuja: require('./png/Goripuja.webp'),
  GauriPuja: require('./png/Goripuja.webp'),
  HoliDehan: require('./png/HoliDehan.webp'),
  HoliDahan: require('./png/HoliDehan.webp'),
  HoliRang: require('./png/HoliRang.webp'),
  Holi: require('./png/HoliRang.webp'),
  JagannathRath: require('./png/JagannathRath.webp'),
  JagannathRathYatra: require('./png/JagannathRath.webp'),
  Shivratri: require('./png/Shivratri.webp'),
  MahaShivratri: require('./png/Shivratri.webp'),
  VasantPanchami: require('./png/VasantPanchami.webp'),
  user: require('./png/user.webp'),
  profile: require('./png/user.webp'),
  pencil: require('./png/pencil.webp'),
  KarnChaPage1: require('./png/KarnChaPage1.webp'),
  KarnChaPage2: require('./png/KarnChaPage2.webp'),
  KarnChaPage3: require('./png/KarnChaPage3.webp'),
  KarnChaPage4: require('./png/KarnChaPage4.webp'),
  KarnChaPage5: require('./png/KarnChaPage5.webp'),
  KarnChaPages: [
    require('./png/KarnChaPage1.webp'),
    require('./png/KarnChaPage2.webp'),
    require('./png/KarnChaPage3.webp'),
    require('./png/KarnChaPage4.webp'),
    require('./png/KarnChaPage5.webp'),
  ],
  KarnChallenge: require('./png/KarnChallenge.webp'),
  AbhimanyuBookCover: require('./png/abimanyu/BookCover.webp'),
  AbhimanyuPage1: require('./png/abimanyu/Page1.webp'),
  AbhimanyuPage2: require('./png/abimanyu/Page2.webp'),
  AbhimanyuPage3: require('./png/abimanyu/Page3.webp'),
  AbhimanyuPage4: require('./png/abimanyu/Page4.webp'),
  AbhimanyuPage5: require('./png/abimanyu/Page5.webp'),
  AbhimanyuPage6: require('./png/abimanyu/Page6.webp'),
  AbhimanyuPage7: require('./png/abimanyu/Page7.webp'),
  AbhimanyuPage8: require('./png/abimanyu/Page8.webp'),
  AbhimanyuPage9: require('./png/abimanyu/Page9.webp'),
  AbhimanyuPage10: require('./png/abimanyu/Page10.webp'),
  AbhimanyuPage11: require('./png/abimanyu/Page11.webp'),
  AbhimanyuPage12: require('./png/abimanyu/Page12.webp'),
  AbhimanyuPage13: require('./png/abimanyu/Page13.webp'),
  AbhimanyuPage15: require('./png/abimanyu/Page15.webp'),
  AbhimanyuPage16: require('./png/abimanyu/Page16.webp'),
  AbhimanyuPage17: require('./png/abimanyu/Page17.webp'),
  AbhimanyuPage18: require('./png/abimanyu/Page18.webp'),
  AbhimanyuPages: [
    require('./png/abimanyu/Page1.webp'),
    require('./png/abimanyu/Page2.webp'),
    require('./png/abimanyu/Page3.webp'),
    require('./png/abimanyu/Page4.webp'),
    require('./png/abimanyu/Page5.webp'),
    require('./png/abimanyu/Page6.webp'),
    require('./png/abimanyu/Page7.webp'),
    require('./png/abimanyu/Page8.webp'),
    require('./png/abimanyu/Page9.webp'),
    require('./png/abimanyu/Page10.webp'),
    require('./png/abimanyu/Page11.webp'),
    require('./png/abimanyu/Page12.webp'),
    require('./png/abimanyu/Page13.webp'),
    require('./png/abimanyu/Page15.webp'),
    require('./png/abimanyu/Page16.webp'),
    require('./png/abimanyu/Page17.webp'),
    require('./png/abimanyu/Page18.webp'),
  ],
  EklavyaCoverPage: require('./png/Eklavya/EklavyaCoverPage.webp'),
  EklavyaPage1: require('./png/Eklavya/EklavyaPage1.webp'),
  EklavyaPage2: require('./png/Eklavya/EklavyaPage2.webp'),
  EklavyaPage3: require('./png/Eklavya/EklavyaPage3.webp'),
  EklavyaPage4: require('./png/Eklavya/EklavyaPage4.webp'),
  EklavyaPage5: require('./png/Eklavya/EklavyaPage5.webp'),
  EklavyaPage6: require('./png/Eklavya/EklavyaPage6.webp'),
  EklavyaPage7: require('./png/Eklavya/EklavyaPage7.webp'),
  EklavyaPage8: require('./png/Eklavya/EklavyaPage8.webp'),
  EklavyaPage9: require('./png/Eklavya/EklavyaPage9.png'),
  EklavyaPage10: require('./png/Eklavya/EklavyaPage10.webp'),
  EklavyaPage11: require('./png/Eklavya/EklavyaPage11.webp'),
  EklavyaPage12: require('./png/Eklavya/EklavyaPage12.webp'),
  EklavyaPage13: require('./png/Eklavya/EklavyaPage13.webp'),
  EklavyaPage14: require('./png/Eklavya/EklavyaPage14.webp'),
  EklavyaPage15: require('./png/Eklavya/EklavyaPage15.webp'),
  EklavyaPages: [
    require('./png/Eklavya/EklavyaPage1.webp'),
    require('./png/Eklavya/EklavyaPage2.webp'),
    require('./png/Eklavya/EklavyaPage3.webp'),
    require('./png/Eklavya/EklavyaPage4.webp'),
    require('./png/Eklavya/EklavyaPage5.webp'),
    require('./png/Eklavya/EklavyaPage6.webp'),
    require('./png/Eklavya/EklavyaPage7.webp'),
    require('./png/Eklavya/EklavyaPage8.webp'),
    require('./png/Eklavya/EklavyaPage9.png'),
    require('./png/Eklavya/EklavyaPage10.webp'),
    require('./png/Eklavya/EklavyaPage11.webp'),
    require('./png/Eklavya/EklavyaPage12.webp'),
    require('./png/Eklavya/EklavyaPage13.webp'),
    require('./png/Eklavya/EklavyaPage14.webp'),
    require('./png/Eklavya/EklavyaPage15.webp'),
  ],
  Logo: require('./png/Logo.webp'),
  Vibration: require('./png/Vibration.webp'),
  VibrationOff: require('./png/VibrationOff.webp'),
  book: require('./png/book.webp'),
  books: require('./png/books.webp'),
  mala: require('./png/mala.webp'),
  star: require('./png/star.webp'),
  warning: require('./png/warning.webp'),
  sakura: require('./png/sakura.webp'),
  calendar: require('./png/calendar.webp'),
  lamp: require('./png/lamp.webp'),
  shlok: require('./png/shlok.webp'),
  temples: require('./png/temples.webp'),
  clock: require('./png/clock.webp'),
};

export { Back, Forward, Bell, Pin, FoldedHands, Location, Tag };
export default imagePath;
