import Back from './svg/Back.svg';
import Forward from './svg/Forward.svg';
import Bell from './svg/bell.svg';

import FoldedHands from './svg/foldedhands.svg';

const imagePath = {
  Back,
  Forward,
  greeting: require('./png/greeting.webp'),
  lotus: require('./png/lotus.webp'),
  Bholenath: require('./png/Bhole.webp'),
  Brahma: require('./png/Bramaji.webp'),
  Durga: require('./png/Durgama.webp'),
  Ganesha: require('./png/Ganesha.webp'),
  Hanuman: require('./png/Hunumanji.webp'),
  Krishna: require('./png/Krishan.webp'),
  Laxmi: require('./png/Laxmima.webp'),
  Rama: require('./png/Ramji.webp'),
  Saraswati: require('./png/Saraswatima.webp'),
  Surya: require('./png/Suryadev.webp'),
  Vishnu: require('./png/Vishnu1.webp'),
  Kubera: require('./png/Kubera.webp'),
  ShaniDev: require('./png/ShaniDev.webp'),
  SriRadha: require('./png/Radhaji.webp'),

  // ID-based God / Mantra image mappings
  shiva: require('./png/Bhole.webp'),
  shiv: require('./png/Bhole.webp'),
  mrityunjaya: require('./png/Bhole.webp'),
  bhole: require('./png/Bhole.webp'),
  bholenath: require('./png/Bhole.webp'),
  mahadev: require('./png/Bhole.webp'),
  vishnu: require('./png/Vishnu1.webp'),
  narayan: require('./png/Vishnu1.webp'),
  krishna: require('./png/Krishan.webp'),
  kanha: require('./png/Krishan.webp'),
  rama: require('./png/Ramji.webp'),
  ram: require('./png/Ramji.webp'),
  shriram: require('./png/Ramji.webp'),
  hanuman: require('./png/Hunumanji.webp'),
  bajrangbali: require('./png/Hunumanji.webp'),
  ganesha: require('./png/Ganesha.webp'),
  ganesh: require('./png/Ganesha.webp'),
  ganpati: require('./png/Ganesha.webp'),
  durga: require('./png/Durgama.webp'),
  ganga: require('./png/Ganga.webp'),
  vishwakarma: require('./png/viswa.webp'),
  kali: require('./png/Kalimaa.webp'),
  laxmi: require('./png/Laxmima.webp'),
  lakshmi: require('./png/Laxmima.webp'),
  saraswati: require('./png/Saraswatima.webp'),
  gayatri: require('./png/Saraswatima.webp'),
  surya: require('./png/Suryadev.webp'),
  brahma: require('./png/Bramaji.webp'),
  shani: require('./png/ShaniDev.webp'),
  shanidev: require('./png/ShaniDev.webp'),
  kubera: require('./png/Kubera.webp'),
  kuber: require('./png/Kubera.webp'),
  radha: require('./png/Radhaji.webp'),

  dhahiHande: require('./png/dhahiHande.webp'),
  nagpachmi: require('./png/nagpachmi.webp'),
  BhaiDhuj: require('./png/BhaiDhuj.webp'),
  BhaiDooj: require('./png/BhaiDhuj.webp'),
  Dashera: require('./png/Dashera.webp'),
  Dussehra: require('./png/Dashera.webp'),
  GaneshChturdi: require('./png/GaneshChturdi.webp'),
  Ganga: require('./png/Ganga.webp'),
  Gangama: require('./png/Ganga.webp'),
  GangaMaa: require('./png/Ganga.webp'),
  GaneshChaturthi: require('./png/GaneshChturdi.webp'),
  GoverDhan: require('./png/GoverDhan.webp'),
  Govardhan: require('./png/GoverDhan.webp'),
  Karwachauth: require('./png/Karwachauth.webp'),
  Kali: require('./png/Kalimaa.webp'),
  Kalima: require('./png/Kalimaa.webp'),
  Kalimaa: require('./png/Kalimaa.webp'),
  KaliMaa: require('./png/Kalimaa.webp'),
  KarwaChauth: require('./png/Karwachauth.webp'),
  Navratri: require('./png/Navratri.webp'),
  RakhiBandan: require('./png/RakhiBandan.webp'),
  RakshaBandhan: require('./png/RakhiBandan.webp'),
  compressedVishnu: require('./png/Vishnu1.webp'),
  Vishwakarma: require('./png/viswa.webp'),
  Viswakarma: require('./png/viswa.webp'),
  OnBoarding: [
    require('./png/OnBoarding1.webp'),
    require('./png/OnBoarding2.webp'),
    require('./png/OnBoarding3.webp'),
  ],

  MalaMoti: require('./png/MalaMoti.webp'),
  Diwali: require('./png/Diwali.webp'),
  Goripuja: require('./festivals/GauriPuja.jpg'),
  GauriPuja: require('./festivals/GauriPuja.jpg'),
  HoliDehan: require('./festivals/HolikaDahan.jpg'),
  HoliDahan: require('./festivals/HolikaDahan.jpg'),
  HolikaDahan: require('./festivals/HolikaDahan.jpg'),
  ChhotiHoli: require('./festivals/ChhotiHoli.jpg'),
  HoliRang: require('./festivals/Holi.jpg'),
  Holi: require('./festivals/Holi.jpg'),
  ShattilaEkadashi: require('./festivals/ShattilaEkadashi.jpg'),
  MakaraSankranti: require('./festivals/MakaraSankranti.jpg'),
  VasantPanchami: require('./festivals/VasantPanchami.jpg'),
  JayaEkadashi: require('./festivals/JayaEkadashi.jpg'),
  VijayaEkadashi: require('./festivals/VijayaEkadashi.jpg'),
  MahaShivaratri: require('./festivals/MahaShivaratri.jpg'),
  AmalakiEkadashi: require('./festivals/AmalakiEkadashi.jpg'),
  PapamochaniEkadashi: require('./festivals/PapamochaniEkadashi.jpg'),
  ChaitraNavratri: require('./festivals/ChaitraNavratri.jpg'),
  JagannathRath: require('./png/JagannathRath.webp'),
  JagannathRathYatra: require('./png/JagannathRath.webp'),
  Shivratri: require('./festivals/MahaShivaratri.jpg'),
  MahaShivratri: require('./festivals/MahaShivaratri.jpg'),

  user: require('./png/user.webp'),
  profile: require('./png/user.webp'),
  pencil: require('./png/pencil.webp'),
  KarnChaPage1: require('./png/KarnChaPage1.webp'),
  KarnChaPage2: require('./png/KarnChaPage2.webp'),
  KarnChaPage3: require('./png/KarnChaPage3.webp'),
  KarnChaPage4: require('./png/KarnChaPage4.webp'),
  KarnChaPage5: require('./png/KarnChaPage5.webp'),
  KarnChaPages: [
    require('./png/KarnChaPage1.webp'),
    require('./png/KarnChaPage2.webp'),
    require('./png/KarnChaPage3.webp'),
    require('./png/KarnChaPage4.webp'),
    require('./png/KarnChaPage5.webp'),
  ],
  KarnChallenge: require('./png/KarnChallenge.webp'),
  AbhimanyuBookCover: require('./png/abimanyu/BookCover.webp'),
  AbhimanyuPage1: require('./png/abimanyu/Page1.webp'),
  AbhimanyuPage2: require('./png/abimanyu/Page2.webp'),
  AbhimanyuPage3: require('./png/abimanyu/Page3.webp'),
  AbhimanyuPage4: require('./png/abimanyu/Page4.webp'),
  AbhimanyuPage5: require('./png/abimanyu/Page5.webp'),
  AbhimanyuPage6: require('./png/abimanyu/Page6.webp'),
  AbhimanyuPage7: require('./png/abimanyu/Page7.webp'),
  AbhimanyuPage8: require('./png/abimanyu/Page8.webp'),
  AbhimanyuPage9: require('./png/abimanyu/Page9.webp'),
  AbhimanyuPage10: require('./png/abimanyu/Page10.webp'),
  AbhimanyuPage11: require('./png/abimanyu/Page11.webp'),
  AbhimanyuPage12: require('./png/abimanyu/Page12.webp'),
  AbhimanyuPage13: require('./png/abimanyu/Page13.webp'),
  AbhimanyuPage15: require('./png/abimanyu/Page15.webp'),
  AbhimanyuPage16: require('./png/abimanyu/Page16.webp'),
  AbhimanyuPage17: require('./png/abimanyu/Page17.webp'),
  AbhimanyuPage18: require('./png/abimanyu/Page18.webp'),
  AbhimanyuPages: [
    require('./png/abimanyu/Page1.webp'),
    require('./png/abimanyu/Page2.webp'),
    require('./png/abimanyu/Page3.webp'),
    require('./png/abimanyu/Page4.webp'),
    require('./png/abimanyu/Page5.webp'),
    require('./png/abimanyu/Page6.webp'),
    require('./png/abimanyu/Page7.webp'),
    require('./png/abimanyu/Page8.webp'),
    require('./png/abimanyu/Page9.webp'),
    require('./png/abimanyu/Page10.webp'),
    require('./png/abimanyu/Page11.webp'),
    require('./png/abimanyu/Page12.webp'),
    require('./png/abimanyu/Page13.webp'),
    require('./png/abimanyu/Page15.webp'),
    require('./png/abimanyu/Page16.webp'),
    require('./png/abimanyu/Page17.webp'),
    require('./png/abimanyu/Page18.webp'),
  ],
  EklavyaCoverPage: require('./png/Eklavya/EklavyaCoverPage.webp'),
  EklavyaPage1: require('./png/Eklavya/EklavyaPage1.webp'),
  EklavyaPage2: require('./png/Eklavya/EklavyaPage2.webp'),
  EklavyaPage3: require('./png/Eklavya/EklavyaPage3.webp'),
  EklavyaPage4: require('./png/Eklavya/EklavyaPage4.webp'),
  EklavyaPage5: require('./png/Eklavya/EklavyaPage5.webp'),
  EklavyaPage6: require('./png/Eklavya/EklavyaPage6.webp'),
  EklavyaPage7: require('./png/Eklavya/EklavyaPage7.webp'),
  EklavyaPage8: require('./png/Eklavya/EklavyaPage8.webp'),
  EklavyaPage9: require('./png/Eklavya/EklavyaPage9.webp'),
  EklavyaPage10: require('./png/Eklavya/EklavyaPage10.webp'),
  EklavyaPage11: require('./png/Eklavya/EklavyaPage11.webp'),
  EklavyaPage12: require('./png/Eklavya/EklavyaPage12.webp'),
  EklavyaPage13: require('./png/Eklavya/EklavyaPage13.webp'),
  EklavyaPage14: require('./png/Eklavya/EklavyaPage14.webp'),
  EklavyaPage15: require('./png/Eklavya/EklavyaPage15.webp'),
  EklavyaPages: [
    require('./png/Eklavya/EklavyaPage1.webp'),
    require('./png/Eklavya/EklavyaPage2.webp'),
    require('./png/Eklavya/EklavyaPage3.webp'),
    require('./png/Eklavya/EklavyaPage4.webp'),
    require('./png/Eklavya/EklavyaPage5.webp'),
    require('./png/Eklavya/EklavyaPage6.webp'),
    require('./png/Eklavya/EklavyaPage7.webp'),
    require('./png/Eklavya/EklavyaPage8.webp'),
    require('./png/Eklavya/EklavyaPage9.webp'),
    require('./png/Eklavya/EklavyaPage10.webp'),
    require('./png/Eklavya/EklavyaPage11.webp'),
    require('./png/Eklavya/EklavyaPage12.webp'),
    require('./png/Eklavya/EklavyaPage13.webp'),
    require('./png/Eklavya/EklavyaPage14.webp'),
    require('./png/Eklavya/EklavyaPage15.webp'),
  ],
  KGCoverPage: require("./png/Karn'sGift/KGCoverPage.webp"),
  KGPage1: require("./png/Karn'sGift/KGPage1.webp"),
  KGPage2: require("./png/Karn'sGift/KGPage2.webp"),
  KGPage3: require("./png/Karn'sGift/KGPage3.webp"),
  KGPage4: require("./png/Karn'sGift/KGPage4.webp"),
  KGPage5: require("./png/Karn'sGift/KGPage5.webp"),
  KGPage6: require("./png/Karn'sGift/KGPage6.webp"),
  KGPage7: require("./png/Karn'sGift/KGPage7.webp"),
  KGPage8: require("./png/Karn'sGift/KGPage8.webp"),
  KGPage9: require("./png/Karn'sGift/KGPage9.webp"),
  KarnGiftPages: [
    require("./png/Karn'sGift/KGPage1.webp"),
    require("./png/Karn'sGift/KGPage2.webp"),
    require("./png/Karn'sGift/KGPage3.webp"),
    require("./png/Karn'sGift/KGPage4.webp"),
    require("./png/Karn'sGift/KGPage5.webp"),
    require("./png/Karn'sGift/KGPage6.webp"),
    require("./png/Karn'sGift/KGPage7.webp"),
    require("./png/Karn'sGift/KGPage8.webp"),
    require("./png/Karn'sGift/KGPage9.webp"),
  ],
  Logo: require('./png/Logo.webp'),
  Vibration: require('./png/Vibration.webp'),
  VibrationOff: require('./png/VibrationOff.webp'),
  book: require('./png/book.webp'),
  books: require('./png/books.webp'),
  mala: require('./png/mala.webp'),
  calendarTab: require('./png/calendarTab.png'),
  star: require('./png/star.webp'),
  warning: require('./png/warning.webp'),

  calendar: require('./png/calendar.webp'),
  lamp: require('./png/lamp.webp'),
  shlok: require('./png/shlok.webp'),
  temples: require('./png/temples.webp'),
  clock: require('./png/clock.webp'),
  temple_bell: require('./png/temple_bell.png'),
  templeBell: require('./png/temple_bell.png'),
  karm: require('./png/karm.jpg'),
  krishnasBirth: require('./png/krishnasBirth.jpg'),
  vasudevaCarriesKrishna: require('./png/vasudevaCarriesKrishna.jpg'),
  dashavataraCover: require('./png/dashavatara/dashavatara_cover.jpg'),
  matsyaAvatar: require('./png/dashavatara/matsya.jpg'),
  kurmaAvatar: require('./png/dashavatara/kurma.jpg'),
  varahaAvatar: require('./png/dashavatara/varaha.jpg'),
  narasimhaAvatar: require('./png/dashavatara/narasimha.jpg'),
  vamanaAvatar: require('./png/dashavatara/vamana.jpg'),
  parashuramaAvatar: require('./png/dashavatara/parashurama.jpg'),
  ramaAvatar: require('./png/dashavatara/rama.jpg'),
  krishnaAvatar: require('./png/dashavatara/krishna.png'),
  buddhaAvatar: require('./png/dashavatara/buddha.jpg'),
  kalkiAvatar: require('./png/dashavatara/kalki.jpg'),
  ganeshJanani: require('./png/ganesha_birth/ganesh_janani.jpg'),
  rebirthOfGanesha: require('./png/ganesha_birth/rebirth_of_ganesha.jpg'),
  shivaParvatiGanesha: require('./png/ganesha_birth/shiva_parvati_ganesha.jpg'),
  ganeshaBlessing: require('./png/ganesha_birth/ganesha_blessing.jpg'),
  prahladaDevotion: require('./png/prahlada_narasimha/prahlada_devotion.jpg'),
  hiranyakashipuPillar: require('./png/prahlada_narasimha/hiranyakashipu_pillar.jpg'),
  narasimhaSlaying: require('./png/prahlada_narasimha/narasimha_slaying.jpg'),
  ramSetuBuilding: require('./png/ram_setu/ram_setu_building.jpg'),
  vanaraRamSetu: require('./png/ram_setu/vanara_ram_setu.jpg'),
  buildingSetuLanka: require('./png/ram_setu/building_setu_lanka.jpg'),
  loading: require('./lottie/loading.json'),
  lampLottie: require('./lottie/lamp.json'),

  // 4 Sacred Char Dham images
  badrinathDham: require('./png/chardham/badrinath.jpg'),
  dwarkadhishDham: require('./png/chardham/dwarka.jpg'),
  jagannathPuriDham: require('./png/chardham/jagannath_puri.jpg'),

  // 12 Sacred Jyotirlinga images
  somnathJyotirlinga: require('./png/jyotirlinga/somnath.jpg'),
  mallikarjunaJyotirlinga: require('./png/jyotirlinga/mallikarjuna.jpg'),
  mahakaleshwarJyotirlinga: require('./png/jyotirlinga/mahakaleshwar.jpg'),
  omkareshwarJyotirlinga: require('./png/jyotirlinga/omkareshwar.jpg'),
  kedarnathJyotirlinga: require('./png/jyotirlinga/kedarnath.jpg'),
  bhimashankarJyotirlinga: require('./png/jyotirlinga/bhimashankar.jpg'),
  kashiVishwanathJyotirlinga: require('./png/jyotirlinga/kashi_vishwanath.jpg'),
  trimbakeshwarJyotirlinga: require('./png/jyotirlinga/trimbakeshwar.jpg'),
  vaidyanathJyotirlinga: require('./png/jyotirlinga/vaidyanath.jpg'),
  nageshwarJyotirlinga: require('./png/jyotirlinga/nageshwar.jpg'),
  rameshwaramJyotirlinga: require('./png/jyotirlinga/rameshwaram.jpg'),
  grishneshwarJyotirlinga: require('./png/jyotirlinga/grishneshwar.jpg'),

  // audio and video
  bhaktiVideo: require('./video/bhakti.mp4'),
  artiDemo: require('./audio/ArtiDemo.mp3'),
};

export { Back, Forward, Bell, FoldedHands };
export default imagePath;
